// Generated by gencpp from file comm_srvs/cameraParam.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_CAMERAPARAM_H
#define COMM_SRVS_MESSAGE_CAMERAPARAM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_srvs
{
template <class ContainerAllocator>
struct cameraParam_
{
  typedef cameraParam_<ContainerAllocator> Type;

  cameraParam_()
    : name_id()
    , port_name()
    , frame_hz(0)
    , height(0)
    , width(0)
    , tx(0.0)
    , ty(0.0)
    , tz(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , camera_matrix()
    , distortion_coefficients()  {
    }
  cameraParam_(const ContainerAllocator& _alloc)
    : name_id(_alloc)
    , port_name(_alloc)
    , frame_hz(0)
    , height(0)
    , width(0)
    , tx(0.0)
    , ty(0.0)
    , tz(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , camera_matrix(_alloc)
    , distortion_coefficients(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_id_type;
  _name_id_type name_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _port_name_type;
  _port_name_type port_name;

   typedef uint32_t _frame_hz_type;
  _frame_hz_type frame_hz;

   typedef uint32_t _height_type;
  _height_type height;

   typedef uint32_t _width_type;
  _width_type width;

   typedef float _tx_type;
  _tx_type tx;

   typedef float _ty_type;
  _ty_type ty;

   typedef float _tz_type;
  _tz_type tz;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _camera_matrix_type;
  _camera_matrix_type camera_matrix;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _distortion_coefficients_type;
  _distortion_coefficients_type distortion_coefficients;





  typedef boost::shared_ptr< ::comm_srvs::cameraParam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::cameraParam_<ContainerAllocator> const> ConstPtr;

}; // struct cameraParam_

typedef ::comm_srvs::cameraParam_<std::allocator<void> > cameraParam;

typedef boost::shared_ptr< ::comm_srvs::cameraParam > cameraParamPtr;
typedef boost::shared_ptr< ::comm_srvs::cameraParam const> cameraParamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::cameraParam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::cameraParam_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::cameraParam_<ContainerAllocator1> & lhs, const ::comm_srvs::cameraParam_<ContainerAllocator2> & rhs)
{
  return lhs.name_id == rhs.name_id &&
    lhs.port_name == rhs.port_name &&
    lhs.frame_hz == rhs.frame_hz &&
    lhs.height == rhs.height &&
    lhs.width == rhs.width &&
    lhs.tx == rhs.tx &&
    lhs.ty == rhs.ty &&
    lhs.tz == rhs.tz &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.camera_matrix == rhs.camera_matrix &&
    lhs.distortion_coefficients == rhs.distortion_coefficients;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::cameraParam_<ContainerAllocator1> & lhs, const ::comm_srvs::cameraParam_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::cameraParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::cameraParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::cameraParam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::cameraParam_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::cameraParam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::cameraParam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::cameraParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f9f9ccd79905f101e4555a21c54abfd";
  }

  static const char* value(const ::comm_srvs::cameraParam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f9f9ccd79905f10ULL;
  static const uint64_t static_value2 = 0x1e4555a21c54abfdULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::cameraParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/cameraParam";
  }

  static const char* value(const ::comm_srvs::cameraParam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::cameraParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string      name_id\n"
"string      port_name\n"
"uint32      frame_hz\n"
"\n"
"uint32      height\n"
"uint32      width\n"
"\n"
"float32     tx\n"
"float32     ty\n"
"float32     tz\n"
"float32     roll\n"
"float32     pitch\n"
"float32     yaw\n"
"\n"
"float64[]   camera_matrix\n"
"float64[]   distortion_coefficients\n"
;
  }

  static const char* value(const ::comm_srvs::cameraParam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::cameraParam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name_id);
      stream.next(m.port_name);
      stream.next(m.frame_hz);
      stream.next(m.height);
      stream.next(m.width);
      stream.next(m.tx);
      stream.next(m.ty);
      stream.next(m.tz);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.camera_matrix);
      stream.next(m.distortion_coefficients);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cameraParam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::cameraParam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::cameraParam_<ContainerAllocator>& v)
  {
    s << indent << "name_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name_id);
    s << indent << "port_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.port_name);
    s << indent << "frame_hz: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frame_hz);
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    s << indent << "tx: ";
    Printer<float>::stream(s, indent + "  ", v.tx);
    s << indent << "ty: ";
    Printer<float>::stream(s, indent + "  ", v.ty);
    s << indent << "tz: ";
    Printer<float>::stream(s, indent + "  ", v.tz);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "camera_matrix[]" << std::endl;
    for (size_t i = 0; i < v.camera_matrix.size(); ++i)
    {
      s << indent << "  camera_matrix[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.camera_matrix[i]);
    }
    s << indent << "distortion_coefficients[]" << std::endl;
    for (size_t i = 0; i < v.distortion_coefficients.size(); ++i)
    {
      s << indent << "  distortion_coefficients[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.distortion_coefficients[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_CAMERAPARAM_H
