// Generated by gencpp from file comm_srvs/camerasParamRequest.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_CAMERASPARAMREQUEST_H
#define COMM_SRVS_MESSAGE_CAMERASPARAMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_srvs
{
template <class ContainerAllocator>
struct camerasParamRequest_
{
  typedef camerasParamRequest_<ContainerAllocator> Type;

  camerasParamRequest_()
    {
    }
  camerasParamRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::comm_srvs::camerasParamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::camerasParamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct camerasParamRequest_

typedef ::comm_srvs::camerasParamRequest_<std::allocator<void> > camerasParamRequest;

typedef boost::shared_ptr< ::comm_srvs::camerasParamRequest > camerasParamRequestPtr;
typedef boost::shared_ptr< ::comm_srvs::camerasParamRequest const> camerasParamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::camerasParamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::camerasParamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::camerasParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::camerasParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::camerasParamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::camerasParamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::camerasParamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::camerasParamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::camerasParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::comm_srvs::camerasParamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::camerasParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/camerasParamRequest";
  }

  static const char* value(const ::comm_srvs::camerasParamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::camerasParamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::comm_srvs::camerasParamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::camerasParamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct camerasParamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::camerasParamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::comm_srvs::camerasParamRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_CAMERASPARAMREQUEST_H
