// Generated by gencpp from file comm_srvs/imuCalibrationRequest.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_IMUCALIBRATIONREQUEST_H
#define COMM_SRVS_MESSAGE_IMUCALIBRATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <comm_srvs/sensorInstallParam.h>

namespace comm_srvs
{
template <class ContainerAllocator>
struct imuCalibrationRequest_
{
  typedef imuCalibrationRequest_<ContainerAllocator> Type;

  imuCalibrationRequest_()
    : imuClbtParam()  {
    }
  imuCalibrationRequest_(const ContainerAllocator& _alloc)
    : imuClbtParam(_alloc)  {
  (void)_alloc;
    }



   typedef  ::comm_srvs::sensorInstallParam_<ContainerAllocator>  _imuClbtParam_type;
  _imuClbtParam_type imuClbtParam;





  typedef boost::shared_ptr< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct imuCalibrationRequest_

typedef ::comm_srvs::imuCalibrationRequest_<std::allocator<void> > imuCalibrationRequest;

typedef boost::shared_ptr< ::comm_srvs::imuCalibrationRequest > imuCalibrationRequestPtr;
typedef boost::shared_ptr< ::comm_srvs::imuCalibrationRequest const> imuCalibrationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::imuCalibrationRequest_<ContainerAllocator1> & lhs, const ::comm_srvs::imuCalibrationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.imuClbtParam == rhs.imuClbtParam;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::imuCalibrationRequest_<ContainerAllocator1> & lhs, const ::comm_srvs::imuCalibrationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "444d7ce317880639a96b68c203549e26";
  }

  static const char* value(const ::comm_srvs::imuCalibrationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x444d7ce317880639ULL;
  static const uint64_t static_value2 = 0xa96b68c203549e26ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/imuCalibrationRequest";
  }

  static const char* value(const ::comm_srvs::imuCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensorInstallParam imuClbtParam\n"
"\n"
"================================================================================\n"
"MSG: comm_srvs/sensorInstallParam\n"
"string  name \n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::comm_srvs::imuCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imuClbtParam);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imuCalibrationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::imuCalibrationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::imuCalibrationRequest_<ContainerAllocator>& v)
  {
    s << indent << "imuClbtParam: ";
    s << std::endl;
    Printer< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >::stream(s, indent + "  ", v.imuClbtParam);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_IMUCALIBRATIONREQUEST_H
