// Generated by gencpp from file comm_srvs/InitPose.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_INITPOSE_H
#define COMM_SRVS_MESSAGE_INITPOSE_H

#include <ros/service_traits.h>


#include <comm_srvs/InitPoseRequest.h>
#include <comm_srvs/InitPoseResponse.h>


namespace comm_srvs
{

struct InitPose
{

typedef InitPoseRequest Request;
typedef InitPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitPose
} // namespace comm_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_srvs::InitPose > {
  static const char* value()
  {
    return "4ea516c50b8e2b735013ac031a10cc9d";
  }

  static const char* value(const ::comm_srvs::InitPose&) { return value(); }
};

template<>
struct DataType< ::comm_srvs::InitPose > {
  static const char* value()
  {
    return "comm_srvs/InitPose";
  }

  static const char* value(const ::comm_srvs::InitPose&) { return value(); }
};


// service_traits::MD5Sum< ::comm_srvs::InitPoseRequest> should match
// service_traits::MD5Sum< ::comm_srvs::InitPose >
template<>
struct MD5Sum< ::comm_srvs::InitPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_srvs::InitPose >::value();
  }
  static const char* value(const ::comm_srvs::InitPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_srvs::InitPoseRequest> should match
// service_traits::DataType< ::comm_srvs::InitPose >
template<>
struct DataType< ::comm_srvs::InitPoseRequest>
{
  static const char* value()
  {
    return DataType< ::comm_srvs::InitPose >::value();
  }
  static const char* value(const ::comm_srvs::InitPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_srvs::InitPoseResponse> should match
// service_traits::MD5Sum< ::comm_srvs::InitPose >
template<>
struct MD5Sum< ::comm_srvs::InitPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_srvs::InitPose >::value();
  }
  static const char* value(const ::comm_srvs::InitPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_srvs::InitPoseResponse> should match
// service_traits::DataType< ::comm_srvs::InitPose >
template<>
struct DataType< ::comm_srvs::InitPoseResponse>
{
  static const char* value()
  {
    return DataType< ::comm_srvs::InitPose >::value();
  }
  static const char* value(const ::comm_srvs::InitPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_SRVS_MESSAGE_INITPOSE_H
