// Generated by gencpp from file comm_srvs/lidarOffsetCalibrationRequest.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_LIDAROFFSETCALIBRATIONREQUEST_H
#define COMM_SRVS_MESSAGE_LIDAROFFSETCALIBRATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <comm_srvs/sensorInstallParam.h>

namespace comm_srvs
{
template <class ContainerAllocator>
struct lidarOffsetCalibrationRequest_
{
  typedef lidarOffsetCalibrationRequest_<ContainerAllocator> Type;

  lidarOffsetCalibrationRequest_()
    : lidarOffsetParam()  {
    }
  lidarOffsetCalibrationRequest_(const ContainerAllocator& _alloc)
    : lidarOffsetParam(_alloc)  {
  (void)_alloc;
    }



   typedef  ::comm_srvs::sensorInstallParam_<ContainerAllocator>  _lidarOffsetParam_type;
  _lidarOffsetParam_type lidarOffsetParam;





  typedef boost::shared_ptr< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct lidarOffsetCalibrationRequest_

typedef ::comm_srvs::lidarOffsetCalibrationRequest_<std::allocator<void> > lidarOffsetCalibrationRequest;

typedef boost::shared_ptr< ::comm_srvs::lidarOffsetCalibrationRequest > lidarOffsetCalibrationRequestPtr;
typedef boost::shared_ptr< ::comm_srvs::lidarOffsetCalibrationRequest const> lidarOffsetCalibrationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator1> & lhs, const ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.lidarOffsetParam == rhs.lidarOffsetParam;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator1> & lhs, const ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a058fba49a87770dedd8fc5190bc8a14";
  }

  static const char* value(const ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa058fba49a87770dULL;
  static const uint64_t static_value2 = 0xedd8fc5190bc8a14ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/lidarOffsetCalibrationRequest";
  }

  static const char* value(const ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensorInstallParam lidarOffsetParam\n"
"\n"
"================================================================================\n"
"MSG: comm_srvs/sensorInstallParam\n"
"string  name \n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lidarOffsetParam);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lidarOffsetCalibrationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::lidarOffsetCalibrationRequest_<ContainerAllocator>& v)
  {
    s << indent << "lidarOffsetParam: ";
    s << std::endl;
    Printer< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >::stream(s, indent + "  ", v.lidarOffsetParam);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_LIDAROFFSETCALIBRATIONREQUEST_H
