// Generated by gencpp from file comm_srvs/lidarCalibrationRequest.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_LIDARCALIBRATIONREQUEST_H
#define COMM_SRVS_MESSAGE_LIDARCALIBRATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <comm_srvs/LidarInstallParam.h>

namespace comm_srvs
{
template <class ContainerAllocator>
struct lidarCalibrationRequest_
{
  typedef lidarCalibrationRequest_<ContainerAllocator> Type;

  lidarCalibrationRequest_()
    : lidarsClbtParam()  {
    }
  lidarCalibrationRequest_(const ContainerAllocator& _alloc)
    : lidarsClbtParam(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::comm_srvs::LidarInstallParam_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_srvs::LidarInstallParam_<ContainerAllocator> >> _lidarsClbtParam_type;
  _lidarsClbtParam_type lidarsClbtParam;





  typedef boost::shared_ptr< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct lidarCalibrationRequest_

typedef ::comm_srvs::lidarCalibrationRequest_<std::allocator<void> > lidarCalibrationRequest;

typedef boost::shared_ptr< ::comm_srvs::lidarCalibrationRequest > lidarCalibrationRequestPtr;
typedef boost::shared_ptr< ::comm_srvs::lidarCalibrationRequest const> lidarCalibrationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator1> & lhs, const ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.lidarsClbtParam == rhs.lidarsClbtParam;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator1> & lhs, const ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "303245169c7a62314dd1620235065c87";
  }

  static const char* value(const ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x303245169c7a6231ULL;
  static const uint64_t static_value2 = 0x4dd1620235065c87ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/lidarCalibrationRequest";
  }

  static const char* value(const ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LidarInstallParam[] lidarsClbtParam\n"
"\n"
"================================================================================\n"
"MSG: comm_srvs/LidarInstallParam\n"
"string  name    #MainLidar BlindLidar BlindLidar2\n"
"string  serialNum\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lidarsClbtParam);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lidarCalibrationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::lidarCalibrationRequest_<ContainerAllocator>& v)
  {
    s << indent << "lidarsClbtParam[]" << std::endl;
    for (size_t i = 0; i < v.lidarsClbtParam.size(); ++i)
    {
      s << indent << "  lidarsClbtParam[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_srvs::LidarInstallParam_<ContainerAllocator> >::stream(s, indent + "    ", v.lidarsClbtParam[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_LIDARCALIBRATIONREQUEST_H
