// Generated by gencpp from file comm_srvs/MappingStart.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_MAPPINGSTART_H
#define COMM_SRVS_MESSAGE_MAPPINGSTART_H

#include <ros/service_traits.h>


#include <comm_srvs/MappingStartRequest.h>
#include <comm_srvs/MappingStartResponse.h>


namespace comm_srvs
{

struct MappingStart
{

typedef MappingStartRequest Request;
typedef MappingStartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MappingStart
} // namespace comm_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_srvs::MappingStart > {
  static const char* value()
  {
    return "50d318bcef824d9f76f338ae7c891086";
  }

  static const char* value(const ::comm_srvs::MappingStart&) { return value(); }
};

template<>
struct DataType< ::comm_srvs::MappingStart > {
  static const char* value()
  {
    return "comm_srvs/MappingStart";
  }

  static const char* value(const ::comm_srvs::MappingStart&) { return value(); }
};


// service_traits::MD5Sum< ::comm_srvs::MappingStartRequest> should match
// service_traits::MD5Sum< ::comm_srvs::MappingStart >
template<>
struct MD5Sum< ::comm_srvs::MappingStartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_srvs::MappingStart >::value();
  }
  static const char* value(const ::comm_srvs::MappingStartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_srvs::MappingStartRequest> should match
// service_traits::DataType< ::comm_srvs::MappingStart >
template<>
struct DataType< ::comm_srvs::MappingStartRequest>
{
  static const char* value()
  {
    return DataType< ::comm_srvs::MappingStart >::value();
  }
  static const char* value(const ::comm_srvs::MappingStartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_srvs::MappingStartResponse> should match
// service_traits::MD5Sum< ::comm_srvs::MappingStart >
template<>
struct MD5Sum< ::comm_srvs::MappingStartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_srvs::MappingStart >::value();
  }
  static const char* value(const ::comm_srvs::MappingStartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_srvs::MappingStartResponse> should match
// service_traits::DataType< ::comm_srvs::MappingStart >
template<>
struct DataType< ::comm_srvs::MappingStartResponse>
{
  static const char* value()
  {
    return DataType< ::comm_srvs::MappingStart >::value();
  }
  static const char* value(const ::comm_srvs::MappingStartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_SRVS_MESSAGE_MAPPINGSTART_H
