// Generated by gencpp from file comm_srvs/PcdNet.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_PCDNET_H
#define COMM_SRVS_MESSAGE_PCDNET_H

#include <ros/service_traits.h>


#include <comm_srvs/PcdNetRequest.h>
#include <comm_srvs/PcdNetResponse.h>


namespace comm_srvs
{

struct PcdNet
{

typedef PcdNetRequest Request;
typedef PcdNetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PcdNet
} // namespace comm_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_srvs::PcdNet > {
  static const char* value()
  {
    return "d49762f82989f849a33296dad5e777da";
  }

  static const char* value(const ::comm_srvs::PcdNet&) { return value(); }
};

template<>
struct DataType< ::comm_srvs::PcdNet > {
  static const char* value()
  {
    return "comm_srvs/PcdNet";
  }

  static const char* value(const ::comm_srvs::PcdNet&) { return value(); }
};


// service_traits::MD5Sum< ::comm_srvs::PcdNetRequest> should match
// service_traits::MD5Sum< ::comm_srvs::PcdNet >
template<>
struct MD5Sum< ::comm_srvs::PcdNetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_srvs::PcdNet >::value();
  }
  static const char* value(const ::comm_srvs::PcdNetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_srvs::PcdNetRequest> should match
// service_traits::DataType< ::comm_srvs::PcdNet >
template<>
struct DataType< ::comm_srvs::PcdNetRequest>
{
  static const char* value()
  {
    return DataType< ::comm_srvs::PcdNet >::value();
  }
  static const char* value(const ::comm_srvs::PcdNetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_srvs::PcdNetResponse> should match
// service_traits::MD5Sum< ::comm_srvs::PcdNet >
template<>
struct MD5Sum< ::comm_srvs::PcdNetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_srvs::PcdNet >::value();
  }
  static const char* value(const ::comm_srvs::PcdNetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_srvs::PcdNetResponse> should match
// service_traits::DataType< ::comm_srvs::PcdNet >
template<>
struct DataType< ::comm_srvs::PcdNetResponse>
{
  static const char* value()
  {
    return DataType< ::comm_srvs::PcdNet >::value();
  }
  static const char* value(const ::comm_srvs::PcdNetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_SRVS_MESSAGE_PCDNET_H
