// Generated by gencpp from file comm_srvs/sensorInstallParam.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_SENSORINSTALLPARAM_H
#define COMM_SRVS_MESSAGE_SENSORINSTALLPARAM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_srvs
{
template <class ContainerAllocator>
struct sensorInstallParam_
{
  typedef sensorInstallParam_<ContainerAllocator> Type;

  sensorInstallParam_()
    : name()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  sensorInstallParam_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::comm_srvs::sensorInstallParam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::sensorInstallParam_<ContainerAllocator> const> ConstPtr;

}; // struct sensorInstallParam_

typedef ::comm_srvs::sensorInstallParam_<std::allocator<void> > sensorInstallParam;

typedef boost::shared_ptr< ::comm_srvs::sensorInstallParam > sensorInstallParamPtr;
typedef boost::shared_ptr< ::comm_srvs::sensorInstallParam const> sensorInstallParamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::sensorInstallParam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::sensorInstallParam_<ContainerAllocator1> & lhs, const ::comm_srvs::sensorInstallParam_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::sensorInstallParam_<ContainerAllocator1> & lhs, const ::comm_srvs::sensorInstallParam_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::sensorInstallParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::sensorInstallParam_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::sensorInstallParam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4694c7f482fc573b14d6260c92b28b4a";
  }

  static const char* value(const ::comm_srvs::sensorInstallParam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4694c7f482fc573bULL;
  static const uint64_t static_value2 = 0x14d6260c92b28b4aULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/sensorInstallParam";
  }

  static const char* value(const ::comm_srvs::sensorInstallParam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string  name \n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::comm_srvs::sensorInstallParam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensorInstallParam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::sensorInstallParam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::sensorInstallParam_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_SENSORINSTALLPARAM_H
