// Generated by gencpp from file comm_srvs/VelocityLevelResponse.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_VELOCITYLEVELRESPONSE_H
#define COMM_SRVS_MESSAGE_VELOCITYLEVELRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_srvs
{
template <class ContainerAllocator>
struct VelocityLevelResponse_
{
  typedef VelocityLevelResponse_<ContainerAllocator> Type;

  VelocityLevelResponse_()
    : success(false)  {
    }
  VelocityLevelResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityLevelResponse_

typedef ::comm_srvs::VelocityLevelResponse_<std::allocator<void> > VelocityLevelResponse;

typedef boost::shared_ptr< ::comm_srvs::VelocityLevelResponse > VelocityLevelResponsePtr;
typedef boost::shared_ptr< ::comm_srvs::VelocityLevelResponse const> VelocityLevelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::VelocityLevelResponse_<ContainerAllocator1> & lhs, const ::comm_srvs::VelocityLevelResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::VelocityLevelResponse_<ContainerAllocator1> & lhs, const ::comm_srvs::VelocityLevelResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::comm_srvs::VelocityLevelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/VelocityLevelResponse";
  }

  static const char* value(const ::comm_srvs::VelocityLevelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool    success\n"
;
  }

  static const char* value(const ::comm_srvs::VelocityLevelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityLevelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::VelocityLevelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::VelocityLevelResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_VELOCITYLEVELRESPONSE_H
