// Generated by gencpp from file comm_srvs/VelocityLevelRequest.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_VELOCITYLEVELREQUEST_H
#define COMM_SRVS_MESSAGE_VELOCITYLEVELREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_srvs
{
template <class ContainerAllocator>
struct VelocityLevelRequest_
{
  typedef VelocityLevelRequest_<ContainerAllocator> Type;

  VelocityLevelRequest_()
    : level(0)  {
    }
  VelocityLevelRequest_(const ContainerAllocator& _alloc)
    : level(0)  {
  (void)_alloc;
    }



   typedef int32_t _level_type;
  _level_type level;





  typedef boost::shared_ptr< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityLevelRequest_

typedef ::comm_srvs::VelocityLevelRequest_<std::allocator<void> > VelocityLevelRequest;

typedef boost::shared_ptr< ::comm_srvs::VelocityLevelRequest > VelocityLevelRequestPtr;
typedef boost::shared_ptr< ::comm_srvs::VelocityLevelRequest const> VelocityLevelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::VelocityLevelRequest_<ContainerAllocator1> & lhs, const ::comm_srvs::VelocityLevelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.level == rhs.level;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::VelocityLevelRequest_<ContainerAllocator1> & lhs, const ::comm_srvs::VelocityLevelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ded14a708dd5929a9ebf864ad17c94f5";
  }

  static const char* value(const ::comm_srvs::VelocityLevelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xded14a708dd5929aULL;
  static const uint64_t static_value2 = 0x9ebf864ad17c94f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/VelocityLevelRequest";
  }

  static const char* value(const ::comm_srvs::VelocityLevelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32   level\n"
;
  }

  static const char* value(const ::comm_srvs::VelocityLevelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.level);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityLevelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::VelocityLevelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::VelocityLevelRequest_<ContainerAllocator>& v)
  {
    s << indent << "level: ";
    Printer<int32_t>::stream(s, indent + "  ", v.level);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_VELOCITYLEVELREQUEST_H
