// Generated by gencpp from file comm_srvs/visionLabelCfg.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_VISIONLABELCFG_H
#define COMM_SRVS_MESSAGE_VISIONLABELCFG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_srvs
{
template <class ContainerAllocator>
struct visionLabelCfg_
{
  typedef visionLabelCfg_<ContainerAllocator> Type;

  visionLabelCfg_()
    : vectDetLabel()
    , vectSegLabel()
    , isSupportThickPipe(false)
    , thickPipeWidth(0.0)  {
    }
  visionLabelCfg_(const ContainerAllocator& _alloc)
    : vectDetLabel(_alloc)
    , vectSegLabel(_alloc)
    , isSupportThickPipe(false)
    , thickPipeWidth(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _vectDetLabel_type;
  _vectDetLabel_type vectDetLabel;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _vectSegLabel_type;
  _vectSegLabel_type vectSegLabel;

   typedef uint8_t _isSupportThickPipe_type;
  _isSupportThickPipe_type isSupportThickPipe;

   typedef float _thickPipeWidth_type;
  _thickPipeWidth_type thickPipeWidth;





  typedef boost::shared_ptr< ::comm_srvs::visionLabelCfg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::visionLabelCfg_<ContainerAllocator> const> ConstPtr;

}; // struct visionLabelCfg_

typedef ::comm_srvs::visionLabelCfg_<std::allocator<void> > visionLabelCfg;

typedef boost::shared_ptr< ::comm_srvs::visionLabelCfg > visionLabelCfgPtr;
typedef boost::shared_ptr< ::comm_srvs::visionLabelCfg const> visionLabelCfgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::visionLabelCfg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::visionLabelCfg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::visionLabelCfg_<ContainerAllocator1> & lhs, const ::comm_srvs::visionLabelCfg_<ContainerAllocator2> & rhs)
{
  return lhs.vectDetLabel == rhs.vectDetLabel &&
    lhs.vectSegLabel == rhs.vectSegLabel &&
    lhs.isSupportThickPipe == rhs.isSupportThickPipe &&
    lhs.thickPipeWidth == rhs.thickPipeWidth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::visionLabelCfg_<ContainerAllocator1> & lhs, const ::comm_srvs::visionLabelCfg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::visionLabelCfg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::visionLabelCfg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::visionLabelCfg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::visionLabelCfg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::visionLabelCfg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::visionLabelCfg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::visionLabelCfg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c57896cd544874b34ea95938d00716d9";
  }

  static const char* value(const ::comm_srvs::visionLabelCfg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc57896cd544874b3ULL;
  static const uint64_t static_value2 = 0x4ea95938d00716d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::visionLabelCfg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/visionLabelCfg";
  }

  static const char* value(const ::comm_srvs::visionLabelCfg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::visionLabelCfg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] vectDetLabel\n"
"uint32[] vectSegLabel\n"
"\n"
"bool    isSupportThickPipe #是否支持粗水管类别\n"
"float32 thickPipeWidth     #粗水管宽度阈值\n"
;
  }

  static const char* value(const ::comm_srvs::visionLabelCfg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::visionLabelCfg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vectDetLabel);
      stream.next(m.vectSegLabel);
      stream.next(m.isSupportThickPipe);
      stream.next(m.thickPipeWidth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct visionLabelCfg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::visionLabelCfg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::visionLabelCfg_<ContainerAllocator>& v)
  {
    s << indent << "vectDetLabel[]" << std::endl;
    for (size_t i = 0; i < v.vectDetLabel.size(); ++i)
    {
      s << indent << "  vectDetLabel[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.vectDetLabel[i]);
    }
    s << indent << "vectSegLabel[]" << std::endl;
    for (size_t i = 0; i < v.vectSegLabel.size(); ++i)
    {
      s << indent << "  vectSegLabel[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.vectSegLabel[i]);
    }
    s << indent << "isSupportThickPipe: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isSupportThickPipe);
    s << indent << "thickPipeWidth: ";
    Printer<float>::stream(s, indent + "  ", v.thickPipeWidth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_VISIONLABELCFG_H
