// Generated by gencpp from file comm_srvs/visionFuncResponse.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_VISIONFUNCRESPONSE_H
#define COMM_SRVS_MESSAGE_VISIONFUNCRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <comm_srvs/visionFuncCfg.h>
#include <comm_srvs/visionLabelCfg.h>

namespace comm_srvs
{
template <class ContainerAllocator>
struct visionFuncResponse_
{
  typedef visionFuncResponse_<ContainerAllocator> Type;

  visionFuncResponse_()
    : success(false)
    , isUseApi(false)
    , visionFuncCfgArray()
    , visionLabelCfg()  {
    }
  visionFuncResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , isUseApi(false)
    , visionFuncCfgArray(_alloc)
    , visionLabelCfg(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef uint8_t _isUseApi_type;
  _isUseApi_type isUseApi;

   typedef std::vector< ::comm_srvs::visionFuncCfg_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >> _visionFuncCfgArray_type;
  _visionFuncCfgArray_type visionFuncCfgArray;

   typedef  ::comm_srvs::visionLabelCfg_<ContainerAllocator>  _visionLabelCfg_type;
  _visionLabelCfg_type visionLabelCfg;





  typedef boost::shared_ptr< ::comm_srvs::visionFuncResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::visionFuncResponse_<ContainerAllocator> const> ConstPtr;

}; // struct visionFuncResponse_

typedef ::comm_srvs::visionFuncResponse_<std::allocator<void> > visionFuncResponse;

typedef boost::shared_ptr< ::comm_srvs::visionFuncResponse > visionFuncResponsePtr;
typedef boost::shared_ptr< ::comm_srvs::visionFuncResponse const> visionFuncResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::visionFuncResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::visionFuncResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::visionFuncResponse_<ContainerAllocator1> & lhs, const ::comm_srvs::visionFuncResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.isUseApi == rhs.isUseApi &&
    lhs.visionFuncCfgArray == rhs.visionFuncCfgArray &&
    lhs.visionLabelCfg == rhs.visionLabelCfg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::visionFuncResponse_<ContainerAllocator1> & lhs, const ::comm_srvs::visionFuncResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::visionFuncResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::visionFuncResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::visionFuncResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::visionFuncResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::visionFuncResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::visionFuncResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::visionFuncResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adf5e73fc1530eec7e82d92a5cfadc9f";
  }

  static const char* value(const ::comm_srvs::visionFuncResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadf5e73fc1530eecULL;
  static const uint64_t static_value2 = 0x7e82d92a5cfadc9fULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::visionFuncResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/visionFuncResponse";
  }

  static const char* value(const ::comm_srvs::visionFuncResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::visionFuncResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool                success\n"
"bool                isUseApi\n"
"visionFuncCfg[]     visionFuncCfgArray\n"
"visionLabelCfg      visionLabelCfg\n"
"\n"
"================================================================================\n"
"MSG: comm_srvs/visionFuncCfg\n"
"uint8   funcId      # 功能ID\n"
"bool    ipu         # 是否使用图像处理单元\n"
"uint8   hz          # 执行频率\n"
"================================================================================\n"
"MSG: comm_srvs/visionLabelCfg\n"
"uint32[] vectDetLabel\n"
"uint32[] vectSegLabel\n"
"\n"
"bool    isSupportThickPipe #是否支持粗水管类别\n"
"float32 thickPipeWidth     #粗水管宽度阈值\n"
;
  }

  static const char* value(const ::comm_srvs::visionFuncResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::visionFuncResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.isUseApi);
      stream.next(m.visionFuncCfgArray);
      stream.next(m.visionLabelCfg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct visionFuncResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::visionFuncResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::visionFuncResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "isUseApi: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isUseApi);
    s << indent << "visionFuncCfgArray[]" << std::endl;
    for (size_t i = 0; i < v.visionFuncCfgArray.size(); ++i)
    {
      s << indent << "  visionFuncCfgArray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >::stream(s, indent + "    ", v.visionFuncCfgArray[i]);
    }
    s << indent << "visionLabelCfg: ";
    s << std::endl;
    Printer< ::comm_srvs::visionLabelCfg_<ContainerAllocator> >::stream(s, indent + "  ", v.visionLabelCfg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_VISIONFUNCRESPONSE_H
