// Generated by gencpp from file comm_srvs/visionFuncSimRequest.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_VISIONFUNCSIMREQUEST_H
#define COMM_SRVS_MESSAGE_VISIONFUNCSIMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_srvs
{
template <class ContainerAllocator>
struct visionFuncSimRequest_
{
  typedef visionFuncSimRequest_<ContainerAllocator> Type;

  visionFuncSimRequest_()
    : qrCodeId(0)
    , funcId(0)
    , isUseIpu(false)
    , hz(0)
    , camera()  {
    }
  visionFuncSimRequest_(const ContainerAllocator& _alloc)
    : qrCodeId(0)
    , funcId(0)
    , isUseIpu(false)
    , hz(0)
    , camera(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _qrCodeId_type;
  _qrCodeId_type qrCodeId;

   typedef uint8_t _funcId_type;
  _funcId_type funcId;

   typedef uint8_t _isUseIpu_type;
  _isUseIpu_type isUseIpu;

   typedef uint8_t _hz_type;
  _hz_type hz;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _camera_type;
  _camera_type camera;





  typedef boost::shared_ptr< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> const> ConstPtr;

}; // struct visionFuncSimRequest_

typedef ::comm_srvs::visionFuncSimRequest_<std::allocator<void> > visionFuncSimRequest;

typedef boost::shared_ptr< ::comm_srvs::visionFuncSimRequest > visionFuncSimRequestPtr;
typedef boost::shared_ptr< ::comm_srvs::visionFuncSimRequest const> visionFuncSimRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::visionFuncSimRequest_<ContainerAllocator1> & lhs, const ::comm_srvs::visionFuncSimRequest_<ContainerAllocator2> & rhs)
{
  return lhs.qrCodeId == rhs.qrCodeId &&
    lhs.funcId == rhs.funcId &&
    lhs.isUseIpu == rhs.isUseIpu &&
    lhs.hz == rhs.hz &&
    lhs.camera == rhs.camera;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::visionFuncSimRequest_<ContainerAllocator1> & lhs, const ::comm_srvs::visionFuncSimRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da544cf58d9de4cf161b40840247c52c";
  }

  static const char* value(const ::comm_srvs::visionFuncSimRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda544cf58d9de4cfULL;
  static const uint64_t static_value2 = 0x161b40840247c52cULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/visionFuncSimRequest";
  }

  static const char* value(const ::comm_srvs::visionFuncSimRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8       qrCodeId\n"
"uint8       funcId\n"
"bool        isUseIpu\n"
"uint8       hz\n"
"string      camera\n"
;
  }

  static const char* value(const ::comm_srvs::visionFuncSimRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.qrCodeId);
      stream.next(m.funcId);
      stream.next(m.isUseIpu);
      stream.next(m.hz);
      stream.next(m.camera);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct visionFuncSimRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::visionFuncSimRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::visionFuncSimRequest_<ContainerAllocator>& v)
  {
    s << indent << "qrCodeId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.qrCodeId);
    s << indent << "funcId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.funcId);
    s << indent << "isUseIpu: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isUseIpu);
    s << indent << "hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hz);
    s << indent << "camera: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.camera);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_VISIONFUNCSIMREQUEST_H
