// Generated by gencpp from file comm_srvs/visionFunc.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_VISIONFUNC_H
#define COMM_SRVS_MESSAGE_VISIONFUNC_H

#include <ros/service_traits.h>


#include <comm_srvs/visionFuncRequest.h>
#include <comm_srvs/visionFuncResponse.h>


namespace comm_srvs
{

struct visionFunc
{

typedef visionFuncRequest Request;
typedef visionFuncResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct visionFunc
} // namespace comm_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_srvs::visionFunc > {
  static const char* value()
  {
    return "adf5e73fc1530eec7e82d92a5cfadc9f";
  }

  static const char* value(const ::comm_srvs::visionFunc&) { return value(); }
};

template<>
struct DataType< ::comm_srvs::visionFunc > {
  static const char* value()
  {
    return "comm_srvs/visionFunc";
  }

  static const char* value(const ::comm_srvs::visionFunc&) { return value(); }
};


// service_traits::MD5Sum< ::comm_srvs::visionFuncRequest> should match
// service_traits::MD5Sum< ::comm_srvs::visionFunc >
template<>
struct MD5Sum< ::comm_srvs::visionFuncRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_srvs::visionFunc >::value();
  }
  static const char* value(const ::comm_srvs::visionFuncRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_srvs::visionFuncRequest> should match
// service_traits::DataType< ::comm_srvs::visionFunc >
template<>
struct DataType< ::comm_srvs::visionFuncRequest>
{
  static const char* value()
  {
    return DataType< ::comm_srvs::visionFunc >::value();
  }
  static const char* value(const ::comm_srvs::visionFuncRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_srvs::visionFuncResponse> should match
// service_traits::MD5Sum< ::comm_srvs::visionFunc >
template<>
struct MD5Sum< ::comm_srvs::visionFuncResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_srvs::visionFunc >::value();
  }
  static const char* value(const ::comm_srvs::visionFuncResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_srvs::visionFuncResponse> should match
// service_traits::DataType< ::comm_srvs::visionFunc >
template<>
struct DataType< ::comm_srvs::visionFuncResponse>
{
  static const char* value()
  {
    return DataType< ::comm_srvs::visionFunc >::value();
  }
  static const char* value(const ::comm_srvs::visionFuncResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_SRVS_MESSAGE_VISIONFUNC_H
