// Generated by gencpp from file comm_srvs/visionFuncCfg.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_VISIONFUNCCFG_H
#define COMM_SRVS_MESSAGE_VISIONFUNCCFG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_srvs
{
template <class ContainerAllocator>
struct visionFuncCfg_
{
  typedef visionFuncCfg_<ContainerAllocator> Type;

  visionFuncCfg_()
    : funcId(0)
    , ipu(false)
    , hz(0)  {
    }
  visionFuncCfg_(const ContainerAllocator& _alloc)
    : funcId(0)
    , ipu(false)
    , hz(0)  {
  (void)_alloc;
    }



   typedef uint8_t _funcId_type;
  _funcId_type funcId;

   typedef uint8_t _ipu_type;
  _ipu_type ipu;

   typedef uint8_t _hz_type;
  _hz_type hz;





  typedef boost::shared_ptr< ::comm_srvs::visionFuncCfg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::visionFuncCfg_<ContainerAllocator> const> ConstPtr;

}; // struct visionFuncCfg_

typedef ::comm_srvs::visionFuncCfg_<std::allocator<void> > visionFuncCfg;

typedef boost::shared_ptr< ::comm_srvs::visionFuncCfg > visionFuncCfgPtr;
typedef boost::shared_ptr< ::comm_srvs::visionFuncCfg const> visionFuncCfgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::visionFuncCfg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::visionFuncCfg_<ContainerAllocator1> & lhs, const ::comm_srvs::visionFuncCfg_<ContainerAllocator2> & rhs)
{
  return lhs.funcId == rhs.funcId &&
    lhs.ipu == rhs.ipu &&
    lhs.hz == rhs.hz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::visionFuncCfg_<ContainerAllocator1> & lhs, const ::comm_srvs::visionFuncCfg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::visionFuncCfg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::visionFuncCfg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::visionFuncCfg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788b771f7f7a06c374a8246119139c2d";
  }

  static const char* value(const ::comm_srvs::visionFuncCfg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788b771f7f7a06c3ULL;
  static const uint64_t static_value2 = 0x74a8246119139c2dULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/visionFuncCfg";
  }

  static const char* value(const ::comm_srvs::visionFuncCfg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8   funcId      # 功能ID\n"
"bool    ipu         # 是否使用图像处理单元\n"
"uint8   hz          # 执行频率\n"
;
  }

  static const char* value(const ::comm_srvs::visionFuncCfg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.funcId);
      stream.next(m.ipu);
      stream.next(m.hz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct visionFuncCfg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::visionFuncCfg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::visionFuncCfg_<ContainerAllocator>& v)
  {
    s << indent << "funcId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.funcId);
    s << indent << "ipu: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ipu);
    s << indent << "hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_VISIONFUNCCFG_H
