// Generated by gencpp from file comm_srvs/visionFuncSimResponse.msg
// DO NOT EDIT!


#ifndef COMM_SRVS_MESSAGE_VISIONFUNCSIMRESPONSE_H
#define COMM_SRVS_MESSAGE_VISIONFUNCSIMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_srvs
{
template <class ContainerAllocator>
struct visionFuncSimResponse_
{
  typedef visionFuncSimResponse_<ContainerAllocator> Type;

  visionFuncSimResponse_()
    : success(false)  {
    }
  visionFuncSimResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> const> ConstPtr;

}; // struct visionFuncSimResponse_

typedef ::comm_srvs::visionFuncSimResponse_<std::allocator<void> > visionFuncSimResponse;

typedef boost::shared_ptr< ::comm_srvs::visionFuncSimResponse > visionFuncSimResponsePtr;
typedef boost::shared_ptr< ::comm_srvs::visionFuncSimResponse const> visionFuncSimResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_srvs::visionFuncSimResponse_<ContainerAllocator1> & lhs, const ::comm_srvs::visionFuncSimResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_srvs::visionFuncSimResponse_<ContainerAllocator1> & lhs, const ::comm_srvs::visionFuncSimResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::comm_srvs::visionFuncSimResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_srvs/visionFuncSimResponse";
  }

  static const char* value(const ::comm_srvs::visionFuncSimResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool        success\n"
;
  }

  static const char* value(const ::comm_srvs::visionFuncSimResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct visionFuncSimResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_srvs::visionFuncSimResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_srvs::visionFuncSimResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_SRVS_MESSAGE_VISIONFUNCSIMRESPONSE_H
