# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from comm_msg/dev_info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class dev_info(genpy.Message):
  _md5sum = "17ff66948ac49c3e03faf3f4e7f62471"
  _type = "comm_msg/dev_info"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# charger state
uint8  chargerMotorState
uint32 chargerMotorTravel

# trash box state
uint8   liftMotorState
uint8   rollMotorState
uint32  leftLiftMotorTravel
uint32  rightLiftMotorTravel
uint32  leftRollMotorTravel
uint32  rightRollMotorTravel
float32 angleSensorOne
float32 angleSensorTwo

# dev state
uint8 isStationEmergeStop
uint8 isManualChargeMode
uint8 proximitySw
uint8 chargeSw
uint8 waterSw
uint8 stationLockSw
uint8 chargerTravelSw
uint8 leftTravelSw
uint8 rightTravelSw

# trash cover state
float32 trashBinCoverOpenAngle"""
  __slots__ = ['chargerMotorState','chargerMotorTravel','liftMotorState','rollMotorState','leftLiftMotorTravel','rightLiftMotorTravel','leftRollMotorTravel','rightRollMotorTravel','angleSensorOne','angleSensorTwo','isStationEmergeStop','isManualChargeMode','proximitySw','chargeSw','waterSw','stationLockSw','chargerTravelSw','leftTravelSw','rightTravelSw','trashBinCoverOpenAngle']
  _slot_types = ['uint8','uint32','uint8','uint8','uint32','uint32','uint32','uint32','float32','float32','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       chargerMotorState,chargerMotorTravel,liftMotorState,rollMotorState,leftLiftMotorTravel,rightLiftMotorTravel,leftRollMotorTravel,rightRollMotorTravel,angleSensorOne,angleSensorTwo,isStationEmergeStop,isManualChargeMode,proximitySw,chargeSw,waterSw,stationLockSw,chargerTravelSw,leftTravelSw,rightTravelSw,trashBinCoverOpenAngle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(dev_info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.chargerMotorState is None:
        self.chargerMotorState = 0
      if self.chargerMotorTravel is None:
        self.chargerMotorTravel = 0
      if self.liftMotorState is None:
        self.liftMotorState = 0
      if self.rollMotorState is None:
        self.rollMotorState = 0
      if self.leftLiftMotorTravel is None:
        self.leftLiftMotorTravel = 0
      if self.rightLiftMotorTravel is None:
        self.rightLiftMotorTravel = 0
      if self.leftRollMotorTravel is None:
        self.leftRollMotorTravel = 0
      if self.rightRollMotorTravel is None:
        self.rightRollMotorTravel = 0
      if self.angleSensorOne is None:
        self.angleSensorOne = 0.
      if self.angleSensorTwo is None:
        self.angleSensorTwo = 0.
      if self.isStationEmergeStop is None:
        self.isStationEmergeStop = 0
      if self.isManualChargeMode is None:
        self.isManualChargeMode = 0
      if self.proximitySw is None:
        self.proximitySw = 0
      if self.chargeSw is None:
        self.chargeSw = 0
      if self.waterSw is None:
        self.waterSw = 0
      if self.stationLockSw is None:
        self.stationLockSw = 0
      if self.chargerTravelSw is None:
        self.chargerTravelSw = 0
      if self.leftTravelSw is None:
        self.leftTravelSw = 0
      if self.rightTravelSw is None:
        self.rightTravelSw = 0
      if self.trashBinCoverOpenAngle is None:
        self.trashBinCoverOpenAngle = 0.
    else:
      self.chargerMotorState = 0
      self.chargerMotorTravel = 0
      self.liftMotorState = 0
      self.rollMotorState = 0
      self.leftLiftMotorTravel = 0
      self.rightLiftMotorTravel = 0
      self.leftRollMotorTravel = 0
      self.rightRollMotorTravel = 0
      self.angleSensorOne = 0.
      self.angleSensorTwo = 0.
      self.isStationEmergeStop = 0
      self.isManualChargeMode = 0
      self.proximitySw = 0
      self.chargeSw = 0
      self.waterSw = 0
      self.stationLockSw = 0
      self.chargerTravelSw = 0
      self.leftTravelSw = 0
      self.rightTravelSw = 0
      self.trashBinCoverOpenAngle = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BI2B4I2f9Bf().pack(_x.chargerMotorState, _x.chargerMotorTravel, _x.liftMotorState, _x.rollMotorState, _x.leftLiftMotorTravel, _x.rightLiftMotorTravel, _x.leftRollMotorTravel, _x.rightRollMotorTravel, _x.angleSensorOne, _x.angleSensorTwo, _x.isStationEmergeStop, _x.isManualChargeMode, _x.proximitySw, _x.chargeSw, _x.waterSw, _x.stationLockSw, _x.chargerTravelSw, _x.leftTravelSw, _x.rightTravelSw, _x.trashBinCoverOpenAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 44
      (_x.chargerMotorState, _x.chargerMotorTravel, _x.liftMotorState, _x.rollMotorState, _x.leftLiftMotorTravel, _x.rightLiftMotorTravel, _x.leftRollMotorTravel, _x.rightRollMotorTravel, _x.angleSensorOne, _x.angleSensorTwo, _x.isStationEmergeStop, _x.isManualChargeMode, _x.proximitySw, _x.chargeSw, _x.waterSw, _x.stationLockSw, _x.chargerTravelSw, _x.leftTravelSw, _x.rightTravelSw, _x.trashBinCoverOpenAngle,) = _get_struct_BI2B4I2f9Bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BI2B4I2f9Bf().pack(_x.chargerMotorState, _x.chargerMotorTravel, _x.liftMotorState, _x.rollMotorState, _x.leftLiftMotorTravel, _x.rightLiftMotorTravel, _x.leftRollMotorTravel, _x.rightRollMotorTravel, _x.angleSensorOne, _x.angleSensorTwo, _x.isStationEmergeStop, _x.isManualChargeMode, _x.proximitySw, _x.chargeSw, _x.waterSw, _x.stationLockSw, _x.chargerTravelSw, _x.leftTravelSw, _x.rightTravelSw, _x.trashBinCoverOpenAngle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 44
      (_x.chargerMotorState, _x.chargerMotorTravel, _x.liftMotorState, _x.rollMotorState, _x.leftLiftMotorTravel, _x.rightLiftMotorTravel, _x.leftRollMotorTravel, _x.rightRollMotorTravel, _x.angleSensorOne, _x.angleSensorTwo, _x.isStationEmergeStop, _x.isManualChargeMode, _x.proximitySw, _x.chargeSw, _x.waterSw, _x.stationLockSw, _x.chargerTravelSw, _x.leftTravelSw, _x.rightTravelSw, _x.trashBinCoverOpenAngle,) = _get_struct_BI2B4I2f9Bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BI2B4I2f9Bf = None
def _get_struct_BI2B4I2f9Bf():
    global _struct_BI2B4I2f9Bf
    if _struct_BI2B4I2f9Bf is None:
        _struct_BI2B4I2f9Bf = struct.Struct("<BI2B4I2f9Bf")
    return _struct_BI2B4I2f9Bf
