# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from comm_msg/movTargetsArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import comm_msg.msg
import std_msgs.msg

class movTargetsArray(genpy.Message):
  _md5sum = "b0324d7e29ce331fa6a17d56ed1c1412"
  _type = "comm_msg/movTargetsArray"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header       header
movTarget[]  movTargetsArray
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: comm_msg/movTarget
uint32  id              #运动目标的id
movPred[] movPredArray  #运动目标的预测信息
================================================================================
MSG: comm_msg/movPred
float64 timeStamp
box     box

================================================================================
MSG: comm_msg/box
label   label   #unknown car motor pede
float32 x       #center x
float32 y       #center y
float32 z       #center z
float32 width   #scale x
float32 length  #scale y
float32 height  #scale z
float32 yaw     #rotated by z, radian(not a angle)
float32 vel_x   #m/s
float32 vel_y   #m/s
float32 vel_z   #m/s
#float32 score   #detection confidence [0,1]
================================================================================
MSG: comm_msg/label
#Note: 枚举类别、枚举值、枚举顺序均不可随意改动，不然md5不匹配，消息将无法正常解析

uint8 UNKNOWN                   = 0     #未知（统一类别）
uint8 PEDESTRIAN                = 1     #行人
uint8 CYCLIST                   = 2     #骑自行车的人
uint8 BICYCLE                   = 3     #自行车（两轮车）
uint8 CAR                       = 4     #汽车
uint8 TRUCK                     = 5     #卡车
uint8 TRAM                      = 6     #有轨电车
uint8 TRICYCLE                  = 7     #三轮车
uint8 BUS                       = 8     #公交车

uint8 LOWOBST                   = 10    #低矮障碍
uint8 ROADEDGE                  = 11    #道路边缘
uint8 PIPELINE                  = 12    #水管管线
uint8 CORDON                    = 13    #警戒线
uint8 TREELAWN                  = 14    #街道绿化带
uint8 THICKPIPE                 = 15    #粗水管
uint8 CORD                      = 16    #电线、缆绳
uint8 SLOPE_PAD                 = 17    #斜坡垫
uint8 SPEED_BUMP                = 18    #减速带

uint8 COVER_SOLID               = 20    #实心井盖
uint8 COVER_HOLLOW              = 21    #栅格井盖
uint8 TRAFFIC_CONE              = 22    #雪糕筒（交通锥）
uint8 METAL_BARRIER             = 23    #金属围栏（铁马）
uint8 MEDIAN_BARRIER            = 24    #栅栏（道路中央隔离带）
uint8 CEREMONIAL_POLE           = 25    #礼宾杆
uint8 BOLLARD                   = 26    #路桩

uint8 GARBAGE                   = 40    #垃圾（统称）
uint8 GARBAGE_BOTTLE            = 41    #瓶子
uint8 GARBAGE_PAPER             = 42    #纸巾
uint8 GARBAGE_BRANCH            = 43    #树枝
uint8 GARBAGE_LEAVES            = 44    #树叶
uint8 GARBAGE_BOUGH             = 45    #粗树枝、长树枝
uint8 GARBAGE_CUP               = 46    #奶茶杯
uint8 GARBAGE_CAN               = 47    #易拉罐
uint8 GARBAGE_CARTON            = 48    #纸盒
uint8 GARBAGE_PACKAGE           = 49    #烟盒
uint8 GARBAGE_BRICK             = 70    #砖块（小砖块）
uint8 GARBAGE_CIGARETTEEND      = 71    #烟头


uint8 TRAFFIC_LIGHT             = 50    #交通灯（统称）
uint8 TRAFFIC_LIGHT_OFF         = 51    #交通灯-关闭
uint8 TRAFFIC_LIGHT_RED         = 52    #交通灯-红灯
uint8 TRAFFIC_LIGHT_GREEN       = 53    #交通灯-绿灯
uint8 TRAFFIC_LIGHT_YELLOW      = 54    #交通灯-黄灯

uint8 TRAFFIC_LIGHT_GROUP       = 55    #交通灯-灯组
uint8 TRAFFIC_LIGHT_OFF_LITE    = 56    #交通灯-关闭（小灯）
uint8 TRAFFIC_LIGHT_RED_LITE    = 57    #交通灯-红灯（小灯）
uint8 TRAFFIC_LIGHT_GREEN_LITE  = 58    #交通灯-绿灯（小灯）
uint8 TRAFFIC_LIGHT_YELLOW_LITE = 59    #交通灯-黄灯（小灯）

uint8 CHARGING_GUN              = 60    #充电枪

uint8 PLACEHOLDER               = 101    #占位符(MAX)

uint8 value"""
  __slots__ = ['header','movTargetsArray']
  _slot_types = ['std_msgs/Header','comm_msg/movTarget[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,movTargetsArray

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(movTargetsArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.movTargetsArray is None:
        self.movTargetsArray = []
    else:
      self.header = std_msgs.msg.Header()
      self.movTargetsArray = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.movTargetsArray)
      buff.write(_struct_I.pack(length))
      for val1 in self.movTargetsArray:
        _x = val1.id
        buff.write(_get_struct_I().pack(_x))
        length = len(val1.movPredArray)
        buff.write(_struct_I.pack(length))
        for val2 in val1.movPredArray:
          _x = val2.timeStamp
          buff.write(_get_struct_d().pack(_x))
          _v1 = val2.box
          _v2 = _v1.label
          _x = _v2.value
          buff.write(_get_struct_B().pack(_x))
          _x = _v1
          buff.write(_get_struct_10f().pack(_x.x, _x.y, _x.z, _x.width, _x.length, _x.height, _x.yaw, _x.vel_x, _x.vel_y, _x.vel_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.movTargetsArray is None:
        self.movTargetsArray = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.movTargetsArray = []
      for i in range(0, length):
        val1 = comm_msg.msg.movTarget()
        start = end
        end += 4
        (val1.id,) = _get_struct_I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.movPredArray = []
        for i in range(0, length):
          val2 = comm_msg.msg.movPred()
          start = end
          end += 8
          (val2.timeStamp,) = _get_struct_d().unpack(str[start:end])
          _v3 = val2.box
          _v4 = _v3.label
          start = end
          end += 1
          (_v4.value,) = _get_struct_B().unpack(str[start:end])
          _x = _v3
          start = end
          end += 40
          (_x.x, _x.y, _x.z, _x.width, _x.length, _x.height, _x.yaw, _x.vel_x, _x.vel_y, _x.vel_z,) = _get_struct_10f().unpack(str[start:end])
          val1.movPredArray.append(val2)
        self.movTargetsArray.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.movTargetsArray)
      buff.write(_struct_I.pack(length))
      for val1 in self.movTargetsArray:
        _x = val1.id
        buff.write(_get_struct_I().pack(_x))
        length = len(val1.movPredArray)
        buff.write(_struct_I.pack(length))
        for val2 in val1.movPredArray:
          _x = val2.timeStamp
          buff.write(_get_struct_d().pack(_x))
          _v5 = val2.box
          _v6 = _v5.label
          _x = _v6.value
          buff.write(_get_struct_B().pack(_x))
          _x = _v5
          buff.write(_get_struct_10f().pack(_x.x, _x.y, _x.z, _x.width, _x.length, _x.height, _x.yaw, _x.vel_x, _x.vel_y, _x.vel_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.movTargetsArray is None:
        self.movTargetsArray = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.movTargetsArray = []
      for i in range(0, length):
        val1 = comm_msg.msg.movTarget()
        start = end
        end += 4
        (val1.id,) = _get_struct_I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.movPredArray = []
        for i in range(0, length):
          val2 = comm_msg.msg.movPred()
          start = end
          end += 8
          (val2.timeStamp,) = _get_struct_d().unpack(str[start:end])
          _v7 = val2.box
          _v8 = _v7.label
          start = end
          end += 1
          (_v8.value,) = _get_struct_B().unpack(str[start:end])
          _x = _v7
          start = end
          end += 40
          (_x.x, _x.y, _x.z, _x.width, _x.length, _x.height, _x.yaw, _x.vel_x, _x.vel_y, _x.vel_z,) = _get_struct_10f().unpack(str[start:end])
          val1.movPredArray.append(val2)
        self.movTargetsArray.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10f = None
def _get_struct_10f():
    global _struct_10f
    if _struct_10f is None:
        _struct_10f = struct.Struct("<10f")
    return _struct_10f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
