# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from comm_msg/pose_score.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import comm_msg.msg

class pose_score(genpy.Message):
  _md5sum = "1ba278e321050d4e0b42ab7a7a69fe0c"
  _type = "comm_msg/pose_score"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 score
pose3D  pose
================================================================================
MSG: comm_msg/pose3D
float32 posX
float32 posY
float32 posZ
float32 roll
float32 pitch
float32 yaw"""
  __slots__ = ['score','pose']
  _slot_types = ['float32','comm_msg/pose3D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       score,pose

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pose_score, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.score is None:
        self.score = 0.
      if self.pose is None:
        self.pose = comm_msg.msg.pose3D()
    else:
      self.score = 0.
      self.pose = comm_msg.msg.pose3D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.score, _x.pose.posX, _x.pose.posY, _x.pose.posZ, _x.pose.roll, _x.pose.pitch, _x.pose.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = comm_msg.msg.pose3D()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.score, _x.pose.posX, _x.pose.posY, _x.pose.posZ, _x.pose.roll, _x.pose.pitch, _x.pose.yaw,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.score, _x.pose.posX, _x.pose.posY, _x.pose.posZ, _x.pose.roll, _x.pose.pitch, _x.pose.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pose is None:
        self.pose = comm_msg.msg.pose3D()
      end = 0
      _x = self
      start = end
      end += 28
      (_x.score, _x.pose.posX, _x.pose.posY, _x.pose.posZ, _x.pose.roll, _x.pose.pitch, _x.pose.yaw,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
