# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from comm_msg/radarTarget.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class radarTarget(genpy.Message):
  _md5sum = "2f0ce27dc024af9302b335afb3187795"
  _type = "comm_msg/radarTarget"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32   targetDistx         # 目标相对于清扫车参考坐标系X轴坐标
float32   targetDisty         # 目标相对于清扫车参考坐标系Y轴坐标
float32   targetVelx          # 目标相对于清扫车参考坐标系X轴速度
float32   targetVely          # 目标相对于清扫车参考坐标系Y轴速度"""
  __slots__ = ['targetDistx','targetDisty','targetVelx','targetVely']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       targetDistx,targetDisty,targetVelx,targetVely

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(radarTarget, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.targetDistx is None:
        self.targetDistx = 0.
      if self.targetDisty is None:
        self.targetDisty = 0.
      if self.targetVelx is None:
        self.targetVelx = 0.
      if self.targetVely is None:
        self.targetVely = 0.
    else:
      self.targetDistx = 0.
      self.targetDisty = 0.
      self.targetVelx = 0.
      self.targetVely = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.targetDistx, _x.targetDisty, _x.targetVelx, _x.targetVely))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.targetDistx, _x.targetDisty, _x.targetVelx, _x.targetVely,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.targetDistx, _x.targetDisty, _x.targetVelx, _x.targetVely))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.targetDistx, _x.targetDisty, _x.targetVelx, _x.targetVely,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
