# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from comm_msg/traffic_light_info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class traffic_light_info(genpy.Message):
  _md5sum = "b4755f326c42173c8ecd115dcd1f1001"
  _type = "comm_msg/traffic_light_info"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8    type           # 交通灯显示类型：1(读秒类型) 2(频闪类型) 3(高频亮灭型)
float32  pos_x          # 交通灯中在地图上的坐标x
float32  pos_y          # 交通灯中在地图上的坐标y
float32  pos_z          # 交通灯中在地图上的坐标z
float32  row_length     # 交通灯横向长度
float32  col_length     # 交通灯纵向长度"""
  __slots__ = ['type','pos_x','pos_y','pos_z','row_length','col_length']
  _slot_types = ['uint8','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       type,pos_x,pos_y,pos_z,row_length,col_length

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(traffic_light_info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.type is None:
        self.type = 0
      if self.pos_x is None:
        self.pos_x = 0.
      if self.pos_y is None:
        self.pos_y = 0.
      if self.pos_z is None:
        self.pos_z = 0.
      if self.row_length is None:
        self.row_length = 0.
      if self.col_length is None:
        self.col_length = 0.
    else:
      self.type = 0
      self.pos_x = 0.
      self.pos_y = 0.
      self.pos_z = 0.
      self.row_length = 0.
      self.col_length = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B5f().pack(_x.type, _x.pos_x, _x.pos_y, _x.pos_z, _x.row_length, _x.col_length))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.type, _x.pos_x, _x.pos_y, _x.pos_z, _x.row_length, _x.col_length,) = _get_struct_B5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B5f().pack(_x.type, _x.pos_x, _x.pos_y, _x.pos_z, _x.row_length, _x.col_length))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.type, _x.pos_x, _x.pos_y, _x.pos_z, _x.row_length, _x.col_length,) = _get_struct_B5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B5f = None
def _get_struct_B5f():
    global _struct_B5f
    if _struct_B5f is None:
        _struct_B5f = struct.Struct("<B5f")
    return _struct_B5f
