# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from comm_msg/trash_box_area_obst_state.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class trash_box_area_obst_state(genpy.Message):
  _md5sum = "4ae1ec08cec9667102da97364468a9db"
  _type = "comm_msg/trash_box_area_obst_state"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# trash box area obst state

bool  isExistHighObstInBoxArea      #  车辆后方在垃圾箱翻起内的区域是否存在高于垃圾箱的障碍物
bool  isExistHighObstOutBoxArea     #  车辆后方在垃圾箱翻起外的区域是否存在高于垃圾箱的障碍物
"""
  __slots__ = ['isExistHighObstInBoxArea','isExistHighObstOutBoxArea']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       isExistHighObstInBoxArea,isExistHighObstOutBoxArea

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(trash_box_area_obst_state, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.isExistHighObstInBoxArea is None:
        self.isExistHighObstInBoxArea = False
      if self.isExistHighObstOutBoxArea is None:
        self.isExistHighObstOutBoxArea = False
    else:
      self.isExistHighObstInBoxArea = False
      self.isExistHighObstOutBoxArea = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.isExistHighObstInBoxArea, _x.isExistHighObstOutBoxArea))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.isExistHighObstInBoxArea, _x.isExistHighObstOutBoxArea,) = _get_struct_2B().unpack(str[start:end])
      self.isExistHighObstInBoxArea = bool(self.isExistHighObstInBoxArea)
      self.isExistHighObstOutBoxArea = bool(self.isExistHighObstOutBoxArea)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.isExistHighObstInBoxArea, _x.isExistHighObstOutBoxArea))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.isExistHighObstInBoxArea, _x.isExistHighObstOutBoxArea,) = _get_struct_2B().unpack(str[start:end])
      self.isExistHighObstInBoxArea = bool(self.isExistHighObstInBoxArea)
      self.isExistHighObstOutBoxArea = bool(self.isExistHighObstOutBoxArea)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
