
(cl:in-package :asdf)

(defsystem "comm_srvs-srv"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :comm_srvs-msg
)
  :components ((:file "_package")
    (:file "InitPose" :depends-on ("_package_InitPose"))
    (:file "_package_InitPose" :depends-on ("_package"))
    (:file "MappingStart" :depends-on ("_package_MappingStart"))
    (:file "_package_MappingStart" :depends-on ("_package"))
    (:file "PcdNet" :depends-on ("_package_PcdNet"))
    (:file "_package_PcdNet" :depends-on ("_package"))
    (:file "VelocityLevel" :depends-on ("_package_VelocityLevel"))
    (:file "_package_VelocityLevel" :depends-on ("_package"))
    (:file "cameraCalibration" :depends-on ("_package_cameraCalibration"))
    (:file "_package_cameraCalibration" :depends-on ("_package"))
    (:file "camerasParam" :depends-on ("_package_camerasParam"))
    (:file "_package_camerasParam" :depends-on ("_package"))
    (:file "imuCalibration" :depends-on ("_package_imuCalibration"))
    (:file "_package_imuCalibration" :depends-on ("_package"))
    (:file "imuOffsetCalibration" :depends-on ("_package_imuOffsetCalibration"))
    (:file "_package_imuOffsetCalibration" :depends-on ("_package"))
    (:file "lidarCalibration" :depends-on ("_package_lidarCalibration"))
    (:file "_package_lidarCalibration" :depends-on ("_package"))
    (:file "lidarOffsetCalibration" :depends-on ("_package_lidarOffsetCalibration"))
    (:file "_package_lidarOffsetCalibration" :depends-on ("_package"))
    (:file "visionFunc" :depends-on ("_package_visionFunc"))
    (:file "_package_visionFunc" :depends-on ("_package"))
    (:file "visionFuncSim" :depends-on ("_package_visionFuncSim"))
    (:file "_package_visionFuncSim" :depends-on ("_package"))
  ))