// Generated by gencpp from file comm_msg/coor2DArray.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_COOR2DARRAY_H
#define COMM_MSG_MESSAGE_COOR2DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <comm_msg/coor2D.h>
#include <comm_msg/coor2D.h>
#include <comm_msg/coor2D.h>
#include <comm_msg/coor2D.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct coor2DArray_
{
  typedef coor2DArray_<ContainerAllocator> Type;

  coor2DArray_()
    : header()
    , isContainForwardObst(0)
    , isContainBackwardObst(0)
    , coor2DArray()
    , coor2DArrayTop()
    , coor2DArrayMid()
    , coor2DArrayDown()  {
    }
  coor2DArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , isContainForwardObst(0)
    , isContainBackwardObst(0)
    , coor2DArray(_alloc)
    , coor2DArrayTop(_alloc)
    , coor2DArrayMid(_alloc)
    , coor2DArrayDown(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _isContainForwardObst_type;
  _isContainForwardObst_type isContainForwardObst;

   typedef uint8_t _isContainBackwardObst_type;
  _isContainBackwardObst_type isContainBackwardObst;

   typedef std::vector< ::comm_msg::coor2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_msg::coor2D_<ContainerAllocator> >> _coor2DArray_type;
  _coor2DArray_type coor2DArray;

   typedef std::vector< ::comm_msg::coor2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_msg::coor2D_<ContainerAllocator> >> _coor2DArrayTop_type;
  _coor2DArrayTop_type coor2DArrayTop;

   typedef std::vector< ::comm_msg::coor2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_msg::coor2D_<ContainerAllocator> >> _coor2DArrayMid_type;
  _coor2DArrayMid_type coor2DArrayMid;

   typedef std::vector< ::comm_msg::coor2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_msg::coor2D_<ContainerAllocator> >> _coor2DArrayDown_type;
  _coor2DArrayDown_type coor2DArrayDown;





  typedef boost::shared_ptr< ::comm_msg::coor2DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::coor2DArray_<ContainerAllocator> const> ConstPtr;

}; // struct coor2DArray_

typedef ::comm_msg::coor2DArray_<std::allocator<void> > coor2DArray;

typedef boost::shared_ptr< ::comm_msg::coor2DArray > coor2DArrayPtr;
typedef boost::shared_ptr< ::comm_msg::coor2DArray const> coor2DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::coor2DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::coor2DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::coor2DArray_<ContainerAllocator1> & lhs, const ::comm_msg::coor2DArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.isContainForwardObst == rhs.isContainForwardObst &&
    lhs.isContainBackwardObst == rhs.isContainBackwardObst &&
    lhs.coor2DArray == rhs.coor2DArray &&
    lhs.coor2DArrayTop == rhs.coor2DArrayTop &&
    lhs.coor2DArrayMid == rhs.coor2DArrayMid &&
    lhs.coor2DArrayDown == rhs.coor2DArrayDown;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::coor2DArray_<ContainerAllocator1> & lhs, const ::comm_msg::coor2DArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::coor2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::coor2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::coor2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::coor2DArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::coor2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::coor2DArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::coor2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c15593ec81512cc55beecc6a469f2978";
  }

  static const char* value(const ::comm_msg::coor2DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc15593ec81512cc5ULL;
  static const uint64_t static_value2 = 0x5beecc6a469f2978ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::coor2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/coor2DArray";
  }

  static const char* value(const ::comm_msg::coor2DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::coor2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header    header\n"
"uint8     isContainForwardObst\n"
"uint8     isContainBackwardObst\n"
"coor2D[]  coor2DArray       #待删除\n"
"coor2D[]  coor2DArrayTop\n"
"coor2D[]  coor2DArrayMid\n"
"coor2D[]  coor2DArrayDown\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: comm_msg/coor2D\n"
"coorLabel   label       #坐标类别\n"
"float32     pos_x\n"
"float32     pos_y\n"
"================================================================================\n"
"MSG: comm_msg/coorLabel\n"
"uint8   UNKNOWN      = 0  #未知\n"
"uint8   STATIC       = 1  #静态\n"
"uint8   DYNAMIC      = 2  #动态\n"
"uint8   HOLLOW_OBST  = 3  #空洞障碍\n"
"uint8   SHORT_HOLD   = 4  #低矮维持\n"
"uint8   COMMON_HOLD  = 5  #常规维持\n"
"uint8   BLIND_SPOT   = 6  #盲区障碍\n"
"uint8   SLOPE_PAD    = 7  #斜坡垫\n"
"uint8   CONTACT_EDGE = 8  #触边障碍\n"
"uint8   TREELAWN     = 9  #绿植障碍\n"
"uint8   ULTRASONIC   = 10 #超声\n"
"\n"
"uint8 value\n"
;
  }

  static const char* value(const ::comm_msg::coor2DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::coor2DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.isContainForwardObst);
      stream.next(m.isContainBackwardObst);
      stream.next(m.coor2DArray);
      stream.next(m.coor2DArrayTop);
      stream.next(m.coor2DArrayMid);
      stream.next(m.coor2DArrayDown);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coor2DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::coor2DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::coor2DArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "isContainForwardObst: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isContainForwardObst);
    s << indent << "isContainBackwardObst: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isContainBackwardObst);
    s << indent << "coor2DArray[]" << std::endl;
    for (size_t i = 0; i < v.coor2DArray.size(); ++i)
    {
      s << indent << "  coor2DArray[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_msg::coor2D_<ContainerAllocator> >::stream(s, indent + "    ", v.coor2DArray[i]);
    }
    s << indent << "coor2DArrayTop[]" << std::endl;
    for (size_t i = 0; i < v.coor2DArrayTop.size(); ++i)
    {
      s << indent << "  coor2DArrayTop[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_msg::coor2D_<ContainerAllocator> >::stream(s, indent + "    ", v.coor2DArrayTop[i]);
    }
    s << indent << "coor2DArrayMid[]" << std::endl;
    for (size_t i = 0; i < v.coor2DArrayMid.size(); ++i)
    {
      s << indent << "  coor2DArrayMid[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_msg::coor2D_<ContainerAllocator> >::stream(s, indent + "    ", v.coor2DArrayMid[i]);
    }
    s << indent << "coor2DArrayDown[]" << std::endl;
    for (size_t i = 0; i < v.coor2DArrayDown.size(); ++i)
    {
      s << indent << "  coor2DArrayDown[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_msg::coor2D_<ContainerAllocator> >::stream(s, indent + "    ", v.coor2DArrayDown[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_COOR2DARRAY_H
