// Generated by gencpp from file comm_msg/customRoute.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_CUSTOMROUTE_H
#define COMM_MSG_MESSAGE_CUSTOMROUTE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct customRoute_
{
  typedef customRoute_<ContainerAllocator> Type;

  customRoute_()
    : pointIndexes()
    , length(0)  {
    }
  customRoute_(const ContainerAllocator& _alloc)
    : pointIndexes(_alloc)
    , length(0)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _pointIndexes_type;
  _pointIndexes_type pointIndexes;

   typedef uint8_t _length_type;
  _length_type length;





  typedef boost::shared_ptr< ::comm_msg::customRoute_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::customRoute_<ContainerAllocator> const> ConstPtr;

}; // struct customRoute_

typedef ::comm_msg::customRoute_<std::allocator<void> > customRoute;

typedef boost::shared_ptr< ::comm_msg::customRoute > customRoutePtr;
typedef boost::shared_ptr< ::comm_msg::customRoute const> customRouteConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::customRoute_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::customRoute_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::customRoute_<ContainerAllocator1> & lhs, const ::comm_msg::customRoute_<ContainerAllocator2> & rhs)
{
  return lhs.pointIndexes == rhs.pointIndexes &&
    lhs.length == rhs.length;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::customRoute_<ContainerAllocator1> & lhs, const ::comm_msg::customRoute_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::customRoute_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::customRoute_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::customRoute_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::customRoute_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::customRoute_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::customRoute_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::customRoute_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d188738b8b3c860e29d2f4955ba5b012";
  }

  static const char* value(const ::comm_msg::customRoute_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd188738b8b3c860eULL;
  static const uint64_t static_value2 = 0x29d2f4955ba5b012ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::customRoute_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/customRoute";
  }

  static const char* value(const ::comm_msg::customRoute_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::customRoute_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#record robot new route that contains a sequence of points; the data is the index of point\n"
"uint32[] pointIndexes\n"
"uint8 length\n"
;
  }

  static const char* value(const ::comm_msg::customRoute_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::customRoute_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pointIndexes);
      stream.next(m.length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct customRoute_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::customRoute_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::customRoute_<ContainerAllocator>& v)
  {
    s << indent << "pointIndexes[]" << std::endl;
    for (size_t i = 0; i < v.pointIndexes.size(); ++i)
    {
      s << indent << "  pointIndexes[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.pointIndexes[i]);
    }
    s << indent << "length: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_CUSTOMROUTE_H
