// Generated by gencpp from file comm_msg/module_abnormal_info.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_MODULE_ABNORMAL_INFO_H
#define COMM_MSG_MESSAGE_MODULE_ABNORMAL_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct module_abnormal_info_
{
  typedef module_abnormal_info_<ContainerAllocator> Type;

  module_abnormal_info_()
    : module(0)
    , errCode(0)  {
    }
  module_abnormal_info_(const ContainerAllocator& _alloc)
    : module(0)
    , errCode(0)  {
  (void)_alloc;
    }



   typedef uint32_t _module_type;
  _module_type module;

   typedef int32_t _errCode_type;
  _errCode_type errCode;





  typedef boost::shared_ptr< ::comm_msg::module_abnormal_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::module_abnormal_info_<ContainerAllocator> const> ConstPtr;

}; // struct module_abnormal_info_

typedef ::comm_msg::module_abnormal_info_<std::allocator<void> > module_abnormal_info;

typedef boost::shared_ptr< ::comm_msg::module_abnormal_info > module_abnormal_infoPtr;
typedef boost::shared_ptr< ::comm_msg::module_abnormal_info const> module_abnormal_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::module_abnormal_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::module_abnormal_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::module_abnormal_info_<ContainerAllocator1> & lhs, const ::comm_msg::module_abnormal_info_<ContainerAllocator2> & rhs)
{
  return lhs.module == rhs.module &&
    lhs.errCode == rhs.errCode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::module_abnormal_info_<ContainerAllocator1> & lhs, const ::comm_msg::module_abnormal_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::module_abnormal_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::module_abnormal_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::module_abnormal_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::module_abnormal_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::module_abnormal_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::module_abnormal_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::module_abnormal_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84ac86691c35a13d550d35161d31a61a";
  }

  static const char* value(const ::comm_msg::module_abnormal_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84ac86691c35a13dULL;
  static const uint64_t static_value2 = 0x550d35161d31a61aULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::module_abnormal_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/module_abnormal_info";
  }

  static const char* value(const ::comm_msg::module_abnormal_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::module_abnormal_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 module\n"
"int32  errCode          # 0 表示正常, 其它都表示异常，后续扩展\n"
;
  }

  static const char* value(const ::comm_msg::module_abnormal_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::module_abnormal_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.module);
      stream.next(m.errCode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct module_abnormal_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::module_abnormal_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::module_abnormal_info_<ContainerAllocator>& v)
  {
    s << indent << "module: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.module);
    s << indent << "errCode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.errCode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_MODULE_ABNORMAL_INFO_H
