// Generated by gencpp from file comm_msg/pose.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_POSE_H
#define COMM_MSG_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct pose_
{
  typedef pose_<ContainerAllocator> Type;

  pose_()
    : px(0.0)
    , py(0.0)
    , pz(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  pose_(const ContainerAllocator& _alloc)
    : px(0.0)
    , py(0.0)
    , pz(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _px_type;
  _px_type px;

   typedef float _py_type;
  _py_type py;

   typedef float _pz_type;
  _pz_type pz;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::comm_msg::pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::pose_<ContainerAllocator> const> ConstPtr;

}; // struct pose_

typedef ::comm_msg::pose_<std::allocator<void> > pose;

typedef boost::shared_ptr< ::comm_msg::pose > posePtr;
typedef boost::shared_ptr< ::comm_msg::pose const> poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::pose_<ContainerAllocator1> & lhs, const ::comm_msg::pose_<ContainerAllocator2> & rhs)
{
  return lhs.px == rhs.px &&
    lhs.py == rhs.py &&
    lhs.pz == rhs.pz &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::pose_<ContainerAllocator1> & lhs, const ::comm_msg::pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4974c257f289cfad706f1b0679063a6b";
  }

  static const char* value(const ::comm_msg::pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4974c257f289cfadULL;
  static const uint64_t static_value2 = 0x706f1b0679063a6bULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/pose";
  }

  static const char* value(const ::comm_msg::pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 px\n"
"float32 py\n"
"float32 pz\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::comm_msg::pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.px);
      stream.next(m.py);
      stream.next(m.pz);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::pose_<ContainerAllocator>& v)
  {
    s << indent << "px: ";
    Printer<float>::stream(s, indent + "  ", v.px);
    s << indent << "py: ";
    Printer<float>::stream(s, indent + "  ", v.py);
    s << indent << "pz: ";
    Printer<float>::stream(s, indent + "  ", v.pz);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_POSE_H
