// Generated by gencpp from file comm_msg/SaveMap.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_SAVEMAP_H
#define COMM_MSG_MESSAGE_SAVEMAP_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct SaveMap_
{
  typedef SaveMap_<ContainerAllocator> Type;

  SaveMap_()
    : flag(0)  {
    }
  SaveMap_(const ContainerAllocator& _alloc)
    : flag(0)  {
  (void)_alloc;
    }



   typedef int32_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::comm_msg::SaveMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::SaveMap_<ContainerAllocator> const> ConstPtr;

}; // struct SaveMap_

typedef ::comm_msg::SaveMap_<std::allocator<void> > SaveMap;

typedef boost::shared_ptr< ::comm_msg::SaveMap > SaveMapPtr;
typedef boost::shared_ptr< ::comm_msg::SaveMap const> SaveMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::SaveMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::SaveMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::SaveMap_<ContainerAllocator1> & lhs, const ::comm_msg::SaveMap_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::SaveMap_<ContainerAllocator1> & lhs, const ::comm_msg::SaveMap_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::SaveMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::SaveMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::SaveMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::SaveMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::SaveMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::SaveMap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::SaveMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa0dbc5596ec12974ea3a17a045b36e0";
  }

  static const char* value(const ::comm_msg::SaveMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa0dbc5596ec1297ULL;
  static const uint64_t static_value2 = 0x4ea3a17a045b36e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::SaveMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/SaveMap";
  }

  static const char* value(const ::comm_msg::SaveMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::SaveMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 flag    #1:save map command\n"
;
  }

  static const char* value(const ::comm_msg::SaveMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::SaveMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::SaveMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::SaveMap_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_SAVEMAP_H
