// Generated by gencpp from file comm_msg/security_redundancy.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_SECURITY_REDUNDANCY_H
#define COMM_MSG_MESSAGE_SECURITY_REDUNDANCY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct security_redundancy_
{
  typedef security_redundancy_<ContainerAllocator> Type;

  security_redundancy_()
    : header()
    , isStopLocationAbnormal(0)
    , isStopCollision(0)  {
    }
  security_redundancy_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , isStopLocationAbnormal(0)
    , isStopCollision(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _isStopLocationAbnormal_type;
  _isStopLocationAbnormal_type isStopLocationAbnormal;

   typedef uint8_t _isStopCollision_type;
  _isStopCollision_type isStopCollision;





  typedef boost::shared_ptr< ::comm_msg::security_redundancy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::security_redundancy_<ContainerAllocator> const> ConstPtr;

}; // struct security_redundancy_

typedef ::comm_msg::security_redundancy_<std::allocator<void> > security_redundancy;

typedef boost::shared_ptr< ::comm_msg::security_redundancy > security_redundancyPtr;
typedef boost::shared_ptr< ::comm_msg::security_redundancy const> security_redundancyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::security_redundancy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::security_redundancy_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::security_redundancy_<ContainerAllocator1> & lhs, const ::comm_msg::security_redundancy_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.isStopLocationAbnormal == rhs.isStopLocationAbnormal &&
    lhs.isStopCollision == rhs.isStopCollision;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::security_redundancy_<ContainerAllocator1> & lhs, const ::comm_msg::security_redundancy_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::security_redundancy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::security_redundancy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::security_redundancy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::security_redundancy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::security_redundancy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::security_redundancy_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::security_redundancy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc488962e3f3ac9e71c3b0975a57ab80";
  }

  static const char* value(const ::comm_msg::security_redundancy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc488962e3f3ac9eULL;
  static const uint64_t static_value2 = 0x71c3b0975a57ab80ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::security_redundancy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/security_redundancy";
  }

  static const char* value(const ::comm_msg::security_redundancy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::security_redundancy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n"
"\n"
"uint8   isStopLocationAbnormal\n"
"uint8   isStopCollision\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::comm_msg::security_redundancy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::security_redundancy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.isStopLocationAbnormal);
      stream.next(m.isStopCollision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct security_redundancy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::security_redundancy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::security_redundancy_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "isStopLocationAbnormal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isStopLocationAbnormal);
    s << indent << "isStopCollision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isStopCollision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_SECURITY_REDUNDANCY_H
