// Generated by gencpp from file comm_msg/wheelSpeed.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_WHEELSPEED_H
#define COMM_MSG_MESSAGE_WHEELSPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct wheelSpeed_
{
  typedef wheelSpeed_<ContainerAllocator> Type;

  wheelSpeed_()
    : leftwheel_speed(0.0)
    , rightwheel_speed(0.0)  {
    }
  wheelSpeed_(const ContainerAllocator& _alloc)
    : leftwheel_speed(0.0)
    , rightwheel_speed(0.0)  {
  (void)_alloc;
    }



   typedef float _leftwheel_speed_type;
  _leftwheel_speed_type leftwheel_speed;

   typedef float _rightwheel_speed_type;
  _rightwheel_speed_type rightwheel_speed;





  typedef boost::shared_ptr< ::comm_msg::wheelSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::wheelSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct wheelSpeed_

typedef ::comm_msg::wheelSpeed_<std::allocator<void> > wheelSpeed;

typedef boost::shared_ptr< ::comm_msg::wheelSpeed > wheelSpeedPtr;
typedef boost::shared_ptr< ::comm_msg::wheelSpeed const> wheelSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::wheelSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::wheelSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::wheelSpeed_<ContainerAllocator1> & lhs, const ::comm_msg::wheelSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.leftwheel_speed == rhs.leftwheel_speed &&
    lhs.rightwheel_speed == rhs.rightwheel_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::wheelSpeed_<ContainerAllocator1> & lhs, const ::comm_msg::wheelSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::wheelSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::wheelSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::wheelSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::wheelSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::wheelSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::wheelSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9d95faf9204c76e50e85451b2bd65f4";
  }

  static const char* value(const ::comm_msg::wheelSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9d95faf9204c76eULL;
  static const uint64_t static_value2 = 0x50e85451b2bd65f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/wheelSpeed";
  }

  static const char* value(const ::comm_msg::wheelSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::wheelSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 leftwheel_speed\n"
"float32 rightwheel_speed\n"
;
  }

  static const char* value(const ::comm_msg::wheelSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::wheelSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.leftwheel_speed);
      stream.next(m.rightwheel_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheelSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::wheelSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::wheelSpeed_<ContainerAllocator>& v)
  {
    s << indent << "leftwheel_speed: ";
    Printer<float>::stream(s, indent + "  ", v.leftwheel_speed);
    s << indent << "rightwheel_speed: ";
    Printer<float>::stream(s, indent + "  ", v.rightwheel_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_WHEELSPEED_H
