// Generated by gencpp from file comm_msg/cameraId.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_CAMERAID_H
#define COMM_MSG_MESSAGE_CAMERAID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct cameraId_
{
  typedef cameraId_<ContainerAllocator> Type;

  cameraId_()
    : value(0)  {
    }
  cameraId_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(no_camera)
  #undef no_camera
#endif
#if defined(_WIN32) && defined(front_upper_camera)
  #undef front_upper_camera
#endif
#if defined(_WIN32) && defined(front_lower_camera)
  #undef front_lower_camera
#endif
#if defined(_WIN32) && defined(front_left_camera)
  #undef front_left_camera
#endif
#if defined(_WIN32) && defined(front_right_camera)
  #undef front_right_camera
#endif
#if defined(_WIN32) && defined(rear_camera)
  #undef rear_camera
#endif
#if defined(_WIN32) && defined(rear_left_camera)
  #undef rear_left_camera
#endif
#if defined(_WIN32) && defined(rear_right_camera)
  #undef rear_right_camera
#endif

  enum {
    no_camera = 0u,
    front_upper_camera = 1u,
    front_lower_camera = 2u,
    front_left_camera = 3u,
    front_right_camera = 4u,
    rear_camera = 5u,
    rear_left_camera = 6u,
    rear_right_camera = 7u,
  };


  typedef boost::shared_ptr< ::comm_msg::cameraId_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::cameraId_<ContainerAllocator> const> ConstPtr;

}; // struct cameraId_

typedef ::comm_msg::cameraId_<std::allocator<void> > cameraId;

typedef boost::shared_ptr< ::comm_msg::cameraId > cameraIdPtr;
typedef boost::shared_ptr< ::comm_msg::cameraId const> cameraIdConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::cameraId_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::cameraId_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::cameraId_<ContainerAllocator1> & lhs, const ::comm_msg::cameraId_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::cameraId_<ContainerAllocator1> & lhs, const ::comm_msg::cameraId_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::cameraId_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::cameraId_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::cameraId_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::cameraId_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::cameraId_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::cameraId_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::cameraId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f5d81160474889b1bccaf1081c5dfa4";
  }

  static const char* value(const ::comm_msg::cameraId_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f5d81160474889bULL;
  static const uint64_t static_value2 = 0x1bccaf1081c5dfa4ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::cameraId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/cameraId";
  }

  static const char* value(const ::comm_msg::cameraId_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::cameraId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 no_camera          = 0\n"
"uint8 front_upper_camera = 1\n"
"uint8 front_lower_camera = 2\n"
"uint8 front_left_camera  = 3\n"
"uint8 front_right_camera = 4\n"
"uint8 rear_camera        = 5\n"
"uint8 rear_left_camera   = 6\n"
"uint8 rear_right_camera  = 7\n"
"\n"
"uint8 value\n"
;
  }

  static const char* value(const ::comm_msg::cameraId_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::cameraId_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cameraId_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::cameraId_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::cameraId_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_CAMERAID_H
