// Generated by gencpp from file comm_msg/coor3D.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_COOR3D_H
#define COMM_MSG_MESSAGE_COOR3D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct coor3D_
{
  typedef coor3D_<ContainerAllocator> Type;

  coor3D_()
    : pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)  {
    }
  coor3D_(const ContainerAllocator& _alloc)
    : pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)  {
  (void)_alloc;
    }



   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;

   typedef float _pos_z_type;
  _pos_z_type pos_z;





  typedef boost::shared_ptr< ::comm_msg::coor3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::coor3D_<ContainerAllocator> const> ConstPtr;

}; // struct coor3D_

typedef ::comm_msg::coor3D_<std::allocator<void> > coor3D;

typedef boost::shared_ptr< ::comm_msg::coor3D > coor3DPtr;
typedef boost::shared_ptr< ::comm_msg::coor3D const> coor3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::coor3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::coor3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::coor3D_<ContainerAllocator1> & lhs, const ::comm_msg::coor3D_<ContainerAllocator2> & rhs)
{
  return lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.pos_z == rhs.pos_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::coor3D_<ContainerAllocator1> & lhs, const ::comm_msg::coor3D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::coor3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::coor3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::coor3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::coor3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::coor3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::coor3D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::coor3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03225cff21da80c8dcb47075eac84a6b";
  }

  static const char* value(const ::comm_msg::coor3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03225cff21da80c8ULL;
  static const uint64_t static_value2 = 0xdcb47075eac84a6bULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::coor3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/coor3D";
  }

  static const char* value(const ::comm_msg::coor3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::coor3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pos_x\n"
"float32 pos_y\n"
"float32 pos_z\n"
;
  }

  static const char* value(const ::comm_msg::coor3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::coor3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.pos_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coor3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::coor3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::coor3D_<ContainerAllocator>& v)
  {
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
    s << indent << "pos_z: ";
    Printer<float>::stream(s, indent + "  ", v.pos_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_COOR3D_H
