// Generated by gencpp from file comm_msg/gpsInfo.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_GPSINFO_H
#define COMM_MSG_MESSAGE_GPSINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct gpsInfo_
{
  typedef gpsInfo_<ContainerAllocator> Type;

  gpsInfo_()
    : header()
    , satelliteNum(0)
    , rsltType(0)
    , longitude(0.0)
    , latitude(0.0)
    , altitude(0.0)
    , yamAngle(0.0)  {
    }
  gpsInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , satelliteNum(0)
    , rsltType(0)
    , longitude(0.0)
    , latitude(0.0)
    , altitude(0.0)
    , yamAngle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _satelliteNum_type;
  _satelliteNum_type satelliteNum;

   typedef uint8_t _rsltType_type;
  _rsltType_type rsltType;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef float _altitude_type;
  _altitude_type altitude;

   typedef float _yamAngle_type;
  _yamAngle_type yamAngle;





  typedef boost::shared_ptr< ::comm_msg::gpsInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::gpsInfo_<ContainerAllocator> const> ConstPtr;

}; // struct gpsInfo_

typedef ::comm_msg::gpsInfo_<std::allocator<void> > gpsInfo;

typedef boost::shared_ptr< ::comm_msg::gpsInfo > gpsInfoPtr;
typedef boost::shared_ptr< ::comm_msg::gpsInfo const> gpsInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::gpsInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::gpsInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::gpsInfo_<ContainerAllocator1> & lhs, const ::comm_msg::gpsInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.satelliteNum == rhs.satelliteNum &&
    lhs.rsltType == rhs.rsltType &&
    lhs.longitude == rhs.longitude &&
    lhs.latitude == rhs.latitude &&
    lhs.altitude == rhs.altitude &&
    lhs.yamAngle == rhs.yamAngle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::gpsInfo_<ContainerAllocator1> & lhs, const ::comm_msg::gpsInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::gpsInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::gpsInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::gpsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::gpsInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::gpsInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::gpsInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::gpsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7af55e227f3750810313d5dec1b64d15";
  }

  static const char* value(const ::comm_msg::gpsInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7af55e227f375081ULL;
  static const uint64_t static_value2 = 0x0313d5dec1b64d15ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::gpsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/gpsInfo";
  }

  static const char* value(const ::comm_msg::gpsInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::gpsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n"
"\n"
"# satellite num\n"
"uint8 satelliteNum\n"
"\n"
"# Rslt Type\n"
"uint8 rsltType\n"
"\n"
"# \n"
"float64 longitude\n"
"float64 latitude\n"
"float32 altitude\n"
"\n"
"#\n"
"float32 yamAngle\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::comm_msg::gpsInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::gpsInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.satelliteNum);
      stream.next(m.rsltType);
      stream.next(m.longitude);
      stream.next(m.latitude);
      stream.next(m.altitude);
      stream.next(m.yamAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gpsInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::gpsInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::gpsInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "satelliteNum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.satelliteNum);
    s << indent << "rsltType: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rsltType);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
    s << indent << "yamAngle: ";
    Printer<float>::stream(s, indent + "  ", v.yamAngle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_GPSINFO_H
