// Generated by gencpp from file comm_msg/move_close_loop_ctrl.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_MOVE_CLOSE_LOOP_CTRL_H
#define COMM_MSG_MESSAGE_MOVE_CLOSE_LOOP_CTRL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct move_close_loop_ctrl_
{
  typedef move_close_loop_ctrl_<ContainerAllocator> Type;

  move_close_loop_ctrl_()
    : plannedSteeringAngle(0.0)
    , plannedMoveLinearVel(0.0)
    , controlSteeringAngle(0.0)
    , controlMoveLinearVel(0.0)
    , measureSteeringAngle(0.0)
    , measureMoveLinearVel(0.0)  {
    }
  move_close_loop_ctrl_(const ContainerAllocator& _alloc)
    : plannedSteeringAngle(0.0)
    , plannedMoveLinearVel(0.0)
    , controlSteeringAngle(0.0)
    , controlMoveLinearVel(0.0)
    , measureSteeringAngle(0.0)
    , measureMoveLinearVel(0.0)  {
  (void)_alloc;
    }



   typedef float _plannedSteeringAngle_type;
  _plannedSteeringAngle_type plannedSteeringAngle;

   typedef float _plannedMoveLinearVel_type;
  _plannedMoveLinearVel_type plannedMoveLinearVel;

   typedef float _controlSteeringAngle_type;
  _controlSteeringAngle_type controlSteeringAngle;

   typedef float _controlMoveLinearVel_type;
  _controlMoveLinearVel_type controlMoveLinearVel;

   typedef float _measureSteeringAngle_type;
  _measureSteeringAngle_type measureSteeringAngle;

   typedef float _measureMoveLinearVel_type;
  _measureMoveLinearVel_type measureMoveLinearVel;





  typedef boost::shared_ptr< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct move_close_loop_ctrl_

typedef ::comm_msg::move_close_loop_ctrl_<std::allocator<void> > move_close_loop_ctrl;

typedef boost::shared_ptr< ::comm_msg::move_close_loop_ctrl > move_close_loop_ctrlPtr;
typedef boost::shared_ptr< ::comm_msg::move_close_loop_ctrl const> move_close_loop_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::move_close_loop_ctrl_<ContainerAllocator1> & lhs, const ::comm_msg::move_close_loop_ctrl_<ContainerAllocator2> & rhs)
{
  return lhs.plannedSteeringAngle == rhs.plannedSteeringAngle &&
    lhs.plannedMoveLinearVel == rhs.plannedMoveLinearVel &&
    lhs.controlSteeringAngle == rhs.controlSteeringAngle &&
    lhs.controlMoveLinearVel == rhs.controlMoveLinearVel &&
    lhs.measureSteeringAngle == rhs.measureSteeringAngle &&
    lhs.measureMoveLinearVel == rhs.measureMoveLinearVel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::move_close_loop_ctrl_<ContainerAllocator1> & lhs, const ::comm_msg::move_close_loop_ctrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e51a1651c7c8b7b7a901faef61d12ad6";
  }

  static const char* value(const ::comm_msg::move_close_loop_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe51a1651c7c8b7b7ULL;
  static const uint64_t static_value2 = 0xa901faef61d12ad6ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/move_close_loop_ctrl";
  }

  static const char* value(const ::comm_msg::move_close_loop_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 plannedSteeringAngle\n"
"float32 plannedMoveLinearVel\n"
"float32 controlSteeringAngle\n"
"float32 controlMoveLinearVel\n"
"float32 measureSteeringAngle\n"
"float32 measureMoveLinearVel\n"
;
  }

  static const char* value(const ::comm_msg::move_close_loop_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plannedSteeringAngle);
      stream.next(m.plannedMoveLinearVel);
      stream.next(m.controlSteeringAngle);
      stream.next(m.controlMoveLinearVel);
      stream.next(m.measureSteeringAngle);
      stream.next(m.measureMoveLinearVel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_close_loop_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::move_close_loop_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::move_close_loop_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "plannedSteeringAngle: ";
    Printer<float>::stream(s, indent + "  ", v.plannedSteeringAngle);
    s << indent << "plannedMoveLinearVel: ";
    Printer<float>::stream(s, indent + "  ", v.plannedMoveLinearVel);
    s << indent << "controlSteeringAngle: ";
    Printer<float>::stream(s, indent + "  ", v.controlSteeringAngle);
    s << indent << "controlMoveLinearVel: ";
    Printer<float>::stream(s, indent + "  ", v.controlMoveLinearVel);
    s << indent << "measureSteeringAngle: ";
    Printer<float>::stream(s, indent + "  ", v.measureSteeringAngle);
    s << indent << "measureMoveLinearVel: ";
    Printer<float>::stream(s, indent + "  ", v.measureMoveLinearVel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_MOVE_CLOSE_LOOP_CTRL_H
