// Generated by gencpp from file comm_msg/nav_ctrl.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_NAV_CTRL_H
#define COMM_MSG_MESSAGE_NAV_CTRL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct nav_ctrl_
{
  typedef nav_ctrl_<ContainerAllocator> Type;

  nav_ctrl_()
    : value(0)  {
    }
  nav_ctrl_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(GARBAGE_DETECT)
  #undef GARBAGE_DETECT
#endif
#if defined(_WIN32) && defined(CONTACT_EDGE)
  #undef CONTACT_EDGE
#endif

  enum {
    GARBAGE_DETECT = 1u,
    CONTACT_EDGE = 2u,
  };


  typedef boost::shared_ptr< ::comm_msg::nav_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::nav_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct nav_ctrl_

typedef ::comm_msg::nav_ctrl_<std::allocator<void> > nav_ctrl;

typedef boost::shared_ptr< ::comm_msg::nav_ctrl > nav_ctrlPtr;
typedef boost::shared_ptr< ::comm_msg::nav_ctrl const> nav_ctrlConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::nav_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::nav_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::nav_ctrl_<ContainerAllocator1> & lhs, const ::comm_msg::nav_ctrl_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::nav_ctrl_<ContainerAllocator1> & lhs, const ::comm_msg::nav_ctrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::nav_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::nav_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::nav_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::nav_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::nav_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::nav_ctrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::nav_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6fe31622265b6df86e8a79eeb6d20fe";
  }

  static const char* value(const ::comm_msg::nav_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6fe31622265b6dfULL;
  static const uint64_t static_value2 = 0x86e8a79eeb6d20feULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::nav_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/nav_ctrl";
  }

  static const char* value(const ::comm_msg::nav_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::nav_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 GARBAGE_DETECT = 1    # 垃圾寻扫\n"
"uint8 CONTACT_EDGE   = 2    # 触边生成障碍物\n"
"\n"
"uint8 value\n"
;
  }

  static const char* value(const ::comm_msg::nav_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::nav_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::nav_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::nav_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_NAV_CTRL_H
