// Generated by gencpp from file comm_msg/nav_algo_info.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_NAV_ALGO_INFO_H
#define COMM_MSG_MESSAGE_NAV_ALGO_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct nav_algo_info_
{
  typedef nav_algo_info_<ContainerAllocator> Type;

  nav_algo_info_()
    : algoType(0)  {
    }
  nav_algo_info_(const ContainerAllocator& _alloc)
    : algoType(0)  {
  (void)_alloc;
    }



   typedef uint8_t _algoType_type;
  _algoType_type algoType;





  typedef boost::shared_ptr< ::comm_msg::nav_algo_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::nav_algo_info_<ContainerAllocator> const> ConstPtr;

}; // struct nav_algo_info_

typedef ::comm_msg::nav_algo_info_<std::allocator<void> > nav_algo_info;

typedef boost::shared_ptr< ::comm_msg::nav_algo_info > nav_algo_infoPtr;
typedef boost::shared_ptr< ::comm_msg::nav_algo_info const> nav_algo_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::nav_algo_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::nav_algo_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::nav_algo_info_<ContainerAllocator1> & lhs, const ::comm_msg::nav_algo_info_<ContainerAllocator2> & rhs)
{
  return lhs.algoType == rhs.algoType;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::nav_algo_info_<ContainerAllocator1> & lhs, const ::comm_msg::nav_algo_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::nav_algo_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::nav_algo_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::nav_algo_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::nav_algo_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::nav_algo_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::nav_algo_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::nav_algo_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5aec186900a8a01b0a68e06489a4999";
  }

  static const char* value(const ::comm_msg::nav_algo_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5aec186900a8a01ULL;
  static const uint64_t static_value2 = 0xb0a68e06489a4999ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::nav_algo_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/nav_algo_info";
  }

  static const char* value(const ::comm_msg::nav_algo_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::nav_algo_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 algoType\n"
;
  }

  static const char* value(const ::comm_msg::nav_algo_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::nav_algo_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.algoType);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_algo_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::nav_algo_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::nav_algo_info_<ContainerAllocator>& v)
  {
    s << indent << "algoType: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.algoType);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_NAV_ALGO_INFO_H
