// Generated by gencpp from file comm_msg/sensorExtriParam.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_SENSOREXTRIPARAM_H
#define COMM_MSG_MESSAGE_SENSOREXTRIPARAM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct sensorExtriParam_
{
  typedef sensorExtriParam_<ContainerAllocator> Type;

  sensorExtriParam_()
    : isSupport(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  sensorExtriParam_(const ContainerAllocator& _alloc)
    : isSupport(false)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _isSupport_type;
  _isSupport_type isSupport;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::comm_msg::sensorExtriParam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::sensorExtriParam_<ContainerAllocator> const> ConstPtr;

}; // struct sensorExtriParam_

typedef ::comm_msg::sensorExtriParam_<std::allocator<void> > sensorExtriParam;

typedef boost::shared_ptr< ::comm_msg::sensorExtriParam > sensorExtriParamPtr;
typedef boost::shared_ptr< ::comm_msg::sensorExtriParam const> sensorExtriParamConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::sensorExtriParam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::sensorExtriParam_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::sensorExtriParam_<ContainerAllocator1> & lhs, const ::comm_msg::sensorExtriParam_<ContainerAllocator2> & rhs)
{
  return lhs.isSupport == rhs.isSupport &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::sensorExtriParam_<ContainerAllocator1> & lhs, const ::comm_msg::sensorExtriParam_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::sensorExtriParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::sensorExtriParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::sensorExtriParam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::sensorExtriParam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::sensorExtriParam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::sensorExtriParam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::sensorExtriParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa8f158cca49b672bebf320f87348d74";
  }

  static const char* value(const ::comm_msg::sensorExtriParam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa8f158cca49b672ULL;
  static const uint64_t static_value2 = 0xbebf320f87348d74ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::sensorExtriParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/sensorExtriParam";
  }

  static const char* value(const ::comm_msg::sensorExtriParam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::sensorExtriParam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isSupport \n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::comm_msg::sensorExtriParam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::sensorExtriParam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isSupport);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensorExtriParam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::sensorExtriParam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::sensorExtriParam_<ContainerAllocator>& v)
  {
    s << indent << "isSupport: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isSupport);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_SENSOREXTRIPARAM_H
