// Generated by gencpp from file comm_msg/visionFuncs.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_VISIONFUNCS_H
#define COMM_MSG_MESSAGE_VISIONFUNCS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <comm_msg/visionFunc.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct visionFuncs_
{
  typedef visionFuncs_<ContainerAllocator> Type;

  visionFuncs_()
    : funcs()  {
    }
  visionFuncs_(const ContainerAllocator& _alloc)
    : funcs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::comm_msg::visionFunc_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_msg::visionFunc_<ContainerAllocator> >> _funcs_type;
  _funcs_type funcs;





  typedef boost::shared_ptr< ::comm_msg::visionFuncs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::visionFuncs_<ContainerAllocator> const> ConstPtr;

}; // struct visionFuncs_

typedef ::comm_msg::visionFuncs_<std::allocator<void> > visionFuncs;

typedef boost::shared_ptr< ::comm_msg::visionFuncs > visionFuncsPtr;
typedef boost::shared_ptr< ::comm_msg::visionFuncs const> visionFuncsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::visionFuncs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::visionFuncs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::visionFuncs_<ContainerAllocator1> & lhs, const ::comm_msg::visionFuncs_<ContainerAllocator2> & rhs)
{
  return lhs.funcs == rhs.funcs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::visionFuncs_<ContainerAllocator1> & lhs, const ::comm_msg::visionFuncs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::visionFuncs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::visionFuncs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::visionFuncs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::visionFuncs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::visionFuncs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::visionFuncs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::visionFuncs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "440c01f662b2f182e9590f3a79f9ac6e";
  }

  static const char* value(const ::comm_msg::visionFuncs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x440c01f662b2f182ULL;
  static const uint64_t static_value2 = 0xe9590f3a79f9ac6eULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::visionFuncs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/visionFuncs";
  }

  static const char* value(const ::comm_msg::visionFuncs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::visionFuncs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visionFunc[]  funcs\n"
"================================================================================\n"
"MSG: comm_msg/visionFunc\n"
"# 功能ID\n"
"uint8 NULL_FUNC   = 0   # NULL\n"
"uint8 QR_CODE_DET = 1   # 二维码检测\n"
"uint8 NET_DET     = 2   # 网络检测\n"
"uint8 NET_SEG     = 3   # 网络分割\n"
"\n"
"# msg\n"
"uint8       funcId      # 功能ID\n"
"bool        ipu         # 是否使用图像处理单元\n"
"uint8       hz          # 执行频率\n"
"string[]    cameras     # 相机ID：front_left(前左), front_mid(前中), front_right(前右), rear_mid(后中) etc.\n"
"label[]     usingLabel  # 当前正在使用的类别标签\n"
"================================================================================\n"
"MSG: comm_msg/label\n"
"#Note: 枚举类别、枚举值、枚举顺序均不可随意改动，不然md5不匹配，消息将无法正常解析\n"
"\n"
"uint8 UNKNOWN                   = 0     #未知（统一类别）\n"
"uint8 PEDESTRIAN                = 1     #行人\n"
"uint8 CYCLIST                   = 2     #骑自行车的人\n"
"uint8 BICYCLE                   = 3     #自行车（两轮车）\n"
"uint8 CAR                       = 4     #汽车\n"
"uint8 TRUCK                     = 5     #卡车\n"
"uint8 TRAM                      = 6     #有轨电车\n"
"uint8 TRICYCLE                  = 7     #三轮车\n"
"uint8 BUS                       = 8     #公交车\n"
"\n"
"uint8 LOWOBST                   = 10    #低矮障碍\n"
"uint8 ROADEDGE                  = 11    #道路边缘\n"
"uint8 PIPELINE                  = 12    #水管管线\n"
"uint8 CORDON                    = 13    #警戒线\n"
"uint8 TREELAWN                  = 14    #街道绿化带\n"
"uint8 THICKPIPE                 = 15    #粗水管\n"
"uint8 CORD                      = 16    #电线、缆绳\n"
"uint8 SLOPE_PAD                 = 17    #斜坡垫\n"
"uint8 SPEED_BUMP                = 18    #减速带\n"
"\n"
"uint8 COVER_SOLID               = 20    #实心井盖\n"
"uint8 COVER_HOLLOW              = 21    #栅格井盖\n"
"uint8 TRAFFIC_CONE              = 22    #雪糕筒（交通锥）\n"
"uint8 METAL_BARRIER             = 23    #金属围栏（铁马）\n"
"uint8 MEDIAN_BARRIER            = 24    #栅栏（道路中央隔离带）\n"
"uint8 CEREMONIAL_POLE           = 25    #礼宾杆\n"
"uint8 BOLLARD                   = 26    #路桩\n"
"\n"
"uint8 GARBAGE                   = 40    #垃圾（统称）\n"
"uint8 GARBAGE_BOTTLE            = 41    #瓶子\n"
"uint8 GARBAGE_PAPER             = 42    #纸巾\n"
"uint8 GARBAGE_BRANCH            = 43    #树枝\n"
"uint8 GARBAGE_LEAVES            = 44    #树叶\n"
"uint8 GARBAGE_BOUGH             = 45    #粗树枝、长树枝\n"
"uint8 GARBAGE_CUP               = 46    #奶茶杯\n"
"uint8 GARBAGE_CAN               = 47    #易拉罐\n"
"uint8 GARBAGE_CARTON            = 48    #纸盒\n"
"uint8 GARBAGE_PACKAGE           = 49    #烟盒\n"
"uint8 GARBAGE_BRICK             = 70    #砖块（小砖块）\n"
"uint8 GARBAGE_CIGARETTEEND      = 71    #烟头\n"
"\n"
"\n"
"uint8 TRAFFIC_LIGHT             = 50    #交通灯（统称）\n"
"uint8 TRAFFIC_LIGHT_OFF         = 51    #交通灯-关闭\n"
"uint8 TRAFFIC_LIGHT_RED         = 52    #交通灯-红灯\n"
"uint8 TRAFFIC_LIGHT_GREEN       = 53    #交通灯-绿灯\n"
"uint8 TRAFFIC_LIGHT_YELLOW      = 54    #交通灯-黄灯\n"
"\n"
"uint8 TRAFFIC_LIGHT_GROUP       = 55    #交通灯-灯组\n"
"uint8 TRAFFIC_LIGHT_OFF_LITE    = 56    #交通灯-关闭（小灯）\n"
"uint8 TRAFFIC_LIGHT_RED_LITE    = 57    #交通灯-红灯（小灯）\n"
"uint8 TRAFFIC_LIGHT_GREEN_LITE  = 58    #交通灯-绿灯（小灯）\n"
"uint8 TRAFFIC_LIGHT_YELLOW_LITE = 59    #交通灯-黄灯（小灯）\n"
"\n"
"uint8 CHARGING_GUN              = 60    #充电枪\n"
"\n"
"uint8 PLACEHOLDER               = 101    #占位符(MAX)\n"
"\n"
"uint8 value\n"
;
  }

  static const char* value(const ::comm_msg::visionFuncs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::visionFuncs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.funcs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct visionFuncs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::visionFuncs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::visionFuncs_<ContainerAllocator>& v)
  {
    s << indent << "funcs[]" << std::endl;
    for (size_t i = 0; i < v.funcs.size(); ++i)
    {
      s << indent << "  funcs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_msg::visionFunc_<ContainerAllocator> >::stream(s, indent + "    ", v.funcs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_VISIONFUNCS_H
