// Generated by gencpp from file comm_msg/visionTask.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_VISIONTASK_H
#define COMM_MSG_MESSAGE_VISIONTASK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct visionTask_
{
  typedef visionTask_<ContainerAllocator> Type;

  visionTask_()
    : qrCodeDet(0)
    , lowObstDet(0)
    , netDet(0)
    , netSeg(0)  {
    }
  visionTask_(const ContainerAllocator& _alloc)
    : qrCodeDet(0)
    , lowObstDet(0)
    , netDet(0)
    , netSeg(0)  {
  (void)_alloc;
    }



   typedef uint8_t _qrCodeDet_type;
  _qrCodeDet_type qrCodeDet;

   typedef uint8_t _lowObstDet_type;
  _lowObstDet_type lowObstDet;

   typedef uint8_t _netDet_type;
  _netDet_type netDet;

   typedef uint8_t _netSeg_type;
  _netSeg_type netSeg;





  typedef boost::shared_ptr< ::comm_msg::visionTask_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::visionTask_<ContainerAllocator> const> ConstPtr;

}; // struct visionTask_

typedef ::comm_msg::visionTask_<std::allocator<void> > visionTask;

typedef boost::shared_ptr< ::comm_msg::visionTask > visionTaskPtr;
typedef boost::shared_ptr< ::comm_msg::visionTask const> visionTaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::visionTask_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::visionTask_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::visionTask_<ContainerAllocator1> & lhs, const ::comm_msg::visionTask_<ContainerAllocator2> & rhs)
{
  return lhs.qrCodeDet == rhs.qrCodeDet &&
    lhs.lowObstDet == rhs.lowObstDet &&
    lhs.netDet == rhs.netDet &&
    lhs.netSeg == rhs.netSeg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::visionTask_<ContainerAllocator1> & lhs, const ::comm_msg::visionTask_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::visionTask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::visionTask_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::visionTask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::visionTask_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::visionTask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::visionTask_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::visionTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5b96bd57128009010166b371b6f9420";
  }

  static const char* value(const ::comm_msg::visionTask_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5b96bd571280090ULL;
  static const uint64_t static_value2 = 0x10166b371b6f9420ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::visionTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/visionTask";
  }

  static const char* value(const ::comm_msg::visionTask_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::visionTask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# vision function    0: off   1: on\n"
"\n"
"uint8   qrCodeDet   #QR code detect\n"
"uint8   lowObstDet  #low obstacle detect\n"
"uint8   netDet      #net detection task\n"
"uint8   netSeg      #net segmentation task\n"
;
  }

  static const char* value(const ::comm_msg::visionTask_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::visionTask_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.qrCodeDet);
      stream.next(m.lowObstDet);
      stream.next(m.netDet);
      stream.next(m.netSeg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct visionTask_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::visionTask_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::visionTask_<ContainerAllocator>& v)
  {
    s << indent << "qrCodeDet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.qrCodeDet);
    s << indent << "lowObstDet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lowObstDet);
    s << indent << "netDet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.netDet);
    s << indent << "netSeg: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.netSeg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_VISIONTASK_H
