(cl:in-package comm_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          ISCONTAINFORWARDOBST-VAL
          ISCONTAINFORWARDOBST
          ISCONTAINBACKWARDOBST-VAL
          ISCONTAINBACKWARDOBST
          COOR2DARRAY-VAL
          COOR2DARRAY
          COOR2DARRAYTOP-VAL
          COOR2DARRAYTOP
          COOR2DARRAYMID-VAL
          COOR2DARRAYMID
          COOR2DARRAYDOWN-VAL
          COOR2DARRAYDOWN
))