(cl:in-package comm_msg-msg)
(cl:export '(PLANNEDSTEERINGANGLE-VAL
          PLANNEDSTEERINGANGLE
          PLANNEDMOVELINEARVEL-VAL
          PLANNEDMOVELINEARVEL
          CONTROLSTEERINGANGLE-VAL
          CONTROLSTEERINGANGLE
          CONTROLMOVELINEARVEL-VAL
          CONTROLMOVELINEARVEL
          MEASURESTEERINGANGLE-VAL
          MEASURESTEERINGANGLE
          MEASUREMOVELINEARVEL-VAL
          MEASUREMOVELINEARVEL
))