(cl:in-package comm_msg-msg)
(cl:export '(HEADER-VAL
          HEADER
          ISEXISTTASK-VAL
          ISEXISTTASK
          ISTELECTRL-VAL
          ISTELECTRL
          ISCLEANING-VAL
          ISCLEANING
          STEERINGANGLE-VAL
          STEERINGANGLE
          MOVELINEARVEL-VAL
          MOVELINEARVEL
          ISMOVESMOOTH-VAL
          ISMOVESMOOTH
          ISSTOPSMOOTH-VAL
          ISSTOPSMOOTH
          ISUSESECURITYREDUNDANCY-VAL
          ISUSESECURITYREDUNDANCY
          ISIGNORELASERDATA-VAL
          ISIGNORELASERDATA
          ISIGNOREULTRASONICDATA-VAL
          ISIGNOREULTRASONICDATA
          PLANNINGMODEL-VAL
          PLANNINGMODEL
          BRUSHMODEL-VAL
          BRUSHMODEL
))