(cl:in-package comm_msg-msg)
(cl:export '(COMMLINKSTATE-VAL
          COMMLINKSTATE
          BUTTONSTATE-VAL
          BUTTONSTATE
          BATTERYSTATE-VAL
          BATTERYSTATE
          BATTERYPERCENT-VAL
          BATTERYPERCENT
          TEMPERATURE-VAL
          TEMPERATURE
          HUMIDITY-VAL
          HUMIDITY
          SMOGALERT-VAL
          SMOGALERT
          PUSHRODPOS-VAL
          PUSHRODPOS
          EMERGENTSTATE-VAL
          EMERGENTSTATE
          ZHISHANCMDSHOW-VAL
          ZHISHANCMDSHOW
          POS_X-VAL
          POS_X
          POS_Y-VAL
          POS_Y
          UDISCM1-VAL
          UDISCM1
          UDISCM2-VAL
          UDISCM2
))