// Generated by gencpp from file comm_msg/boxArray.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_BOXARRAY_H
#define COMM_MSG_MESSAGE_BOXARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <comm_msg/box.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct boxArray_
{
  typedef boxArray_<ContainerAllocator> Type;

  boxArray_()
    : header()
    , boxes()  {
    }
  boxArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , boxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::comm_msg::box_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_msg::box_<ContainerAllocator> >> _boxes_type;
  _boxes_type boxes;





  typedef boost::shared_ptr< ::comm_msg::boxArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::boxArray_<ContainerAllocator> const> ConstPtr;

}; // struct boxArray_

typedef ::comm_msg::boxArray_<std::allocator<void> > boxArray;

typedef boost::shared_ptr< ::comm_msg::boxArray > boxArrayPtr;
typedef boost::shared_ptr< ::comm_msg::boxArray const> boxArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::boxArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::boxArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::boxArray_<ContainerAllocator1> & lhs, const ::comm_msg::boxArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.boxes == rhs.boxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::boxArray_<ContainerAllocator1> & lhs, const ::comm_msg::boxArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::boxArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::boxArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::boxArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::boxArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::boxArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::boxArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::boxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c75b4d4a4c4616720356b181655ca74f";
  }

  static const char* value(const ::comm_msg::boxArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc75b4d4a4c461672ULL;
  static const uint64_t static_value2 = 0x0356b181655ca74fULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::boxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/boxArray";
  }

  static const char* value(const ::comm_msg::boxArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::boxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n"
"box[]   boxes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: comm_msg/box\n"
"label   label   #unknown car motor pede\n"
"float32 x       #center x\n"
"float32 y       #center y\n"
"float32 z       #center z\n"
"float32 width   #scale x\n"
"float32 length  #scale y\n"
"float32 height  #scale z\n"
"float32 yaw     #rotated by z, radian(not a angle)\n"
"float32 vel_x   #m/s\n"
"float32 vel_y   #m/s\n"
"float32 vel_z   #m/s\n"
"================================================================================\n"
"MSG: comm_msg/label\n"
"#Note: 枚举类别、枚举值、枚举顺序均不可随意改动，不然md5不匹配，消息将无法正常解析\n"
"\n"
"uint8 UNKNOWN                   = 0     #未知（统一类别）\n"
"uint8 PEDESTRIAN                = 1     #行人\n"
"uint8 CYCLIST                   = 2     #骑自行车的人\n"
"uint8 BICYCLE                   = 3     #自行车（两轮车）\n"
"uint8 CAR                       = 4     #汽车\n"
"uint8 TRUCK                     = 5     #卡车\n"
"uint8 TRAM                      = 6     #有轨电车\n"
"uint8 TRICYCLE                  = 7     #三轮车\n"
"uint8 BUS                       = 8     #公交车\n"
"\n"
"uint8 LOWOBST                   = 10    #低矮障碍\n"
"uint8 ROADEDGE                  = 11    #道路边缘\n"
"uint8 PIPELINE                  = 12    #水管管线\n"
"uint8 CORDON                    = 13    #警戒线\n"
"uint8 TREELAWN                  = 14    #街道绿化带\n"
"uint8 THICKPIPE                 = 15    #粗水管\n"
"uint8 CORD                      = 16    #电线、缆绳\n"
"uint8 SLOPE_PAD                 = 17    #斜坡垫\n"
"uint8 SPEED_BUMP                = 18    #减速带\n"
"\n"
"uint8 COVER_SOLID               = 20    #实心井盖\n"
"uint8 COVER_HOLLOW              = 21    #栅格井盖\n"
"uint8 TRAFFIC_CONE              = 22    #雪糕筒（交通锥）\n"
"uint8 METAL_BARRIER             = 23    #金属围栏（铁马）\n"
"uint8 MEDIAN_BARRIER            = 24    #栅栏（道路中央隔离带）\n"
"uint8 CEREMONIAL_POLE           = 25    #礼宾杆\n"
"uint8 BOLLARD                   = 26    #路桩\n"
"\n"
"uint8 GARBAGE                   = 40    #垃圾（统称）\n"
"uint8 GARBAGE_BOTTLE            = 41    #瓶子\n"
"uint8 GARBAGE_PAPER             = 42    #纸巾\n"
"uint8 GARBAGE_BRANCH            = 43    #树枝\n"
"uint8 GARBAGE_LEAVES            = 44    #树叶\n"
"uint8 GARBAGE_BOUGH             = 45    #粗树枝、长树枝\n"
"uint8 GARBAGE_CUP               = 46    #奶茶杯\n"
"uint8 GARBAGE_CAN               = 47    #易拉罐\n"
"uint8 GARBAGE_CARTON            = 48    #纸盒\n"
"uint8 GARBAGE_PACKAGE           = 49    #烟盒\n"
"uint8 GARBAGE_BRICK             = 70    #砖块（小砖块）\n"
"uint8 GARBAGE_CIGARETTEEND      = 71    #烟头\n"
"\n"
"\n"
"uint8 TRAFFIC_LIGHT             = 50    #交通灯（统称）\n"
"uint8 TRAFFIC_LIGHT_OFF         = 51    #交通灯-关闭\n"
"uint8 TRAFFIC_LIGHT_RED         = 52    #交通灯-红灯\n"
"uint8 TRAFFIC_LIGHT_GREEN       = 53    #交通灯-绿灯\n"
"uint8 TRAFFIC_LIGHT_YELLOW      = 54    #交通灯-黄灯\n"
"\n"
"uint8 TRAFFIC_LIGHT_GROUP       = 55    #交通灯-灯组\n"
"uint8 TRAFFIC_LIGHT_OFF_LITE    = 56    #交通灯-关闭（小灯）\n"
"uint8 TRAFFIC_LIGHT_RED_LITE    = 57    #交通灯-红灯（小灯）\n"
"uint8 TRAFFIC_LIGHT_GREEN_LITE  = 58    #交通灯-绿灯（小灯）\n"
"uint8 TRAFFIC_LIGHT_YELLOW_LITE = 59    #交通灯-黄灯（小灯）\n"
"\n"
"uint8 CHARGING_GUN              = 60    #充电枪\n"
"\n"
"uint8 PLACEHOLDER               = 101    #占位符(MAX)\n"
"\n"
"uint8 value\n"
;
  }

  static const char* value(const ::comm_msg::boxArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::boxArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.boxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct boxArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::boxArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::boxArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "boxes[]" << std::endl;
    for (size_t i = 0; i < v.boxes.size(); ++i)
    {
      s << indent << "  boxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_msg::box_<ContainerAllocator> >::stream(s, indent + "    ", v.boxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_BOXARRAY_H
