// Generated by gencpp from file comm_msg/coor2DArrayLA.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_COOR2DARRAYLA_H
#define COMM_MSG_MESSAGE_COOR2DARRAYLA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <comm_msg/coor2DArrayL.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct coor2DArrayLA_
{
  typedef coor2DArrayLA_<ContainerAllocator> Type;

  coor2DArrayLA_()
    : hasRisk(false)
    , coor2DArrayLA()  {
    }
  coor2DArrayLA_(const ContainerAllocator& _alloc)
    : hasRisk(false)
    , coor2DArrayLA(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _hasRisk_type;
  _hasRisk_type hasRisk;

   typedef std::vector< ::comm_msg::coor2DArrayL_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_msg::coor2DArrayL_<ContainerAllocator> >> _coor2DArrayLA_type;
  _coor2DArrayLA_type coor2DArrayLA;





  typedef boost::shared_ptr< ::comm_msg::coor2DArrayLA_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::coor2DArrayLA_<ContainerAllocator> const> ConstPtr;

}; // struct coor2DArrayLA_

typedef ::comm_msg::coor2DArrayLA_<std::allocator<void> > coor2DArrayLA;

typedef boost::shared_ptr< ::comm_msg::coor2DArrayLA > coor2DArrayLAPtr;
typedef boost::shared_ptr< ::comm_msg::coor2DArrayLA const> coor2DArrayLAConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::coor2DArrayLA_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::coor2DArrayLA_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::coor2DArrayLA_<ContainerAllocator1> & lhs, const ::comm_msg::coor2DArrayLA_<ContainerAllocator2> & rhs)
{
  return lhs.hasRisk == rhs.hasRisk &&
    lhs.coor2DArrayLA == rhs.coor2DArrayLA;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::coor2DArrayLA_<ContainerAllocator1> & lhs, const ::comm_msg::coor2DArrayLA_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::coor2DArrayLA_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::coor2DArrayLA_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::coor2DArrayLA_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::coor2DArrayLA_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::coor2DArrayLA_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::coor2DArrayLA_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::coor2DArrayLA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e90f0a07eab5e228d174cb357ff43632";
  }

  static const char* value(const ::comm_msg::coor2DArrayLA_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe90f0a07eab5e228ULL;
  static const uint64_t static_value2 = 0xd174cb357ff43632ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::coor2DArrayLA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/coor2DArrayLA";
  }

  static const char* value(const ::comm_msg::coor2DArrayLA_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::coor2DArrayLA_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool              hasRisk       #图像视野有无风险，如有风险，需要规控减速\n"
"coor2DArrayL[]    coor2DArrayLA\n"
"================================================================================\n"
"MSG: comm_msg/coor2DArrayL\n"
"Header      header\n"
"label       label\n"
"uint8       id\n"
"coor2D[]    coor2DArray\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: comm_msg/label\n"
"#Note: 枚举类别、枚举值、枚举顺序均不可随意改动，不然md5不匹配，消息将无法正常解析\n"
"\n"
"uint8 UNKNOWN                   = 0     #未知（统一类别）\n"
"uint8 PEDESTRIAN                = 1     #行人\n"
"uint8 CYCLIST                   = 2     #骑自行车的人\n"
"uint8 BICYCLE                   = 3     #自行车（两轮车）\n"
"uint8 CAR                       = 4     #汽车\n"
"uint8 TRUCK                     = 5     #卡车\n"
"uint8 TRAM                      = 6     #有轨电车\n"
"uint8 TRICYCLE                  = 7     #三轮车\n"
"uint8 BUS                       = 8     #公交车\n"
"\n"
"uint8 LOWOBST                   = 10    #低矮障碍\n"
"uint8 ROADEDGE                  = 11    #道路边缘\n"
"uint8 PIPELINE                  = 12    #水管管线\n"
"uint8 CORDON                    = 13    #警戒线\n"
"uint8 TREELAWN                  = 14    #街道绿化带\n"
"uint8 THICKPIPE                 = 15    #粗水管\n"
"uint8 CORD                      = 16    #电线、缆绳\n"
"uint8 SLOPE_PAD                 = 17    #斜坡垫\n"
"uint8 SPEED_BUMP                = 18    #减速带\n"
"\n"
"uint8 COVER_SOLID               = 20    #实心井盖\n"
"uint8 COVER_HOLLOW              = 21    #栅格井盖\n"
"uint8 TRAFFIC_CONE              = 22    #雪糕筒（交通锥）\n"
"uint8 METAL_BARRIER             = 23    #金属围栏（铁马）\n"
"uint8 MEDIAN_BARRIER            = 24    #栅栏（道路中央隔离带）\n"
"uint8 CEREMONIAL_POLE           = 25    #礼宾杆\n"
"uint8 BOLLARD                   = 26    #路桩\n"
"\n"
"uint8 GARBAGE                   = 40    #垃圾（统称）\n"
"uint8 GARBAGE_BOTTLE            = 41    #瓶子\n"
"uint8 GARBAGE_PAPER             = 42    #纸巾\n"
"uint8 GARBAGE_BRANCH            = 43    #树枝\n"
"uint8 GARBAGE_LEAVES            = 44    #树叶\n"
"uint8 GARBAGE_BOUGH             = 45    #粗树枝、长树枝\n"
"uint8 GARBAGE_CUP               = 46    #奶茶杯\n"
"uint8 GARBAGE_CAN               = 47    #易拉罐\n"
"uint8 GARBAGE_CARTON            = 48    #纸盒\n"
"uint8 GARBAGE_PACKAGE           = 49    #烟盒\n"
"uint8 GARBAGE_BRICK             = 70    #砖块（小砖块）\n"
"uint8 GARBAGE_CIGARETTEEND      = 71    #烟头\n"
"\n"
"\n"
"uint8 TRAFFIC_LIGHT             = 50    #交通灯（统称）\n"
"uint8 TRAFFIC_LIGHT_OFF         = 51    #交通灯-关闭\n"
"uint8 TRAFFIC_LIGHT_RED         = 52    #交通灯-红灯\n"
"uint8 TRAFFIC_LIGHT_GREEN       = 53    #交通灯-绿灯\n"
"uint8 TRAFFIC_LIGHT_YELLOW      = 54    #交通灯-黄灯\n"
"\n"
"uint8 TRAFFIC_LIGHT_GROUP       = 55    #交通灯-灯组\n"
"uint8 TRAFFIC_LIGHT_OFF_LITE    = 56    #交通灯-关闭（小灯）\n"
"uint8 TRAFFIC_LIGHT_RED_LITE    = 57    #交通灯-红灯（小灯）\n"
"uint8 TRAFFIC_LIGHT_GREEN_LITE  = 58    #交通灯-绿灯（小灯）\n"
"uint8 TRAFFIC_LIGHT_YELLOW_LITE = 59    #交通灯-黄灯（小灯）\n"
"\n"
"uint8 CHARGING_GUN              = 60    #充电枪\n"
"\n"
"uint8 PLACEHOLDER               = 101    #占位符(MAX)\n"
"\n"
"uint8 value\n"
"================================================================================\n"
"MSG: comm_msg/coor2D\n"
"coorLabel   label       #坐标类别\n"
"float32     pos_x\n"
"float32     pos_y\n"
"================================================================================\n"
"MSG: comm_msg/coorLabel\n"
"uint8   UNKNOWN      = 0  #未知\n"
"uint8   STATIC       = 1  #静态\n"
"uint8   DYNAMIC      = 2  #动态\n"
"uint8   HOLLOW_OBST  = 3  #空洞障碍\n"
"uint8   SHORT_HOLD   = 4  #低矮维持\n"
"uint8   COMMON_HOLD  = 5  #常规维持\n"
"uint8   BLIND_SPOT   = 6  #盲区障碍\n"
"uint8   SLOPE_PAD    = 7  #斜坡垫\n"
"uint8   CONTACT_EDGE = 8  #触边障碍\n"
"uint8   TREELAWN     = 9  #绿植障碍\n"
"uint8   ULTRASONIC   = 10 #超声\n"
"\n"
"uint8 value\n"
;
  }

  static const char* value(const ::comm_msg::coor2DArrayLA_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::coor2DArrayLA_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hasRisk);
      stream.next(m.coor2DArrayLA);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coor2DArrayLA_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::coor2DArrayLA_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::coor2DArrayLA_<ContainerAllocator>& v)
  {
    s << indent << "hasRisk: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hasRisk);
    s << indent << "coor2DArrayLA[]" << std::endl;
    for (size_t i = 0; i < v.coor2DArrayLA.size(); ++i)
    {
      s << indent << "  coor2DArrayLA[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_msg::coor2DArrayL_<ContainerAllocator> >::stream(s, indent + "    ", v.coor2DArrayLA[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_COOR2DARRAYLA_H
