// Generated by gencpp from file comm_msg/daq_ctrl.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_DAQ_CTRL_H
#define COMM_MSG_MESSAGE_DAQ_CTRL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct daq_ctrl_
{
  typedef daq_ctrl_<ContainerAllocator> Type;

  daq_ctrl_()
    : daq_fusion(false)
    , daq_hz(0)
    , daq_camera()
    , daq_lidar()  {
    }
  daq_ctrl_(const ContainerAllocator& _alloc)
    : daq_fusion(false)
    , daq_hz(0)
    , daq_camera(_alloc)
    , daq_lidar(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _daq_fusion_type;
  _daq_fusion_type daq_fusion;

   typedef uint8_t _daq_hz_type;
  _daq_hz_type daq_hz;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _daq_camera_type;
  _daq_camera_type daq_camera;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _daq_lidar_type;
  _daq_lidar_type daq_lidar;





  typedef boost::shared_ptr< ::comm_msg::daq_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::daq_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct daq_ctrl_

typedef ::comm_msg::daq_ctrl_<std::allocator<void> > daq_ctrl;

typedef boost::shared_ptr< ::comm_msg::daq_ctrl > daq_ctrlPtr;
typedef boost::shared_ptr< ::comm_msg::daq_ctrl const> daq_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::daq_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::daq_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::daq_ctrl_<ContainerAllocator1> & lhs, const ::comm_msg::daq_ctrl_<ContainerAllocator2> & rhs)
{
  return lhs.daq_fusion == rhs.daq_fusion &&
    lhs.daq_hz == rhs.daq_hz &&
    lhs.daq_camera == rhs.daq_camera &&
    lhs.daq_lidar == rhs.daq_lidar;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::daq_ctrl_<ContainerAllocator1> & lhs, const ::comm_msg::daq_ctrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::daq_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::daq_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::daq_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::daq_ctrl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::daq_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::daq_ctrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::daq_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b65aad8c511a16f789728648f67ea4d6";
  }

  static const char* value(const ::comm_msg::daq_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb65aad8c511a16f7ULL;
  static const uint64_t static_value2 = 0x89728648f67ea4d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::daq_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/daq_ctrl";
  }

  static const char* value(const ::comm_msg::daq_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::daq_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# e.g. begin: rostopic pub -r 1 /daq_ctrl comm_msg/daq_ctrl \"{daq_fusion: 1, daq_hz: 1, daq_camera:[1,2,3,4,5,6,7,8,9,10], daq_lidar:[1,2,3,4,5]}\"     # 相机+雷达：时间戳需对齐\n"
"# e.g. begin: rostopic pub -r 1 /daq_ctrl comm_msg/daq_ctrl \"{daq_fusion: 0, daq_hz: 1, daq_camera:[1,2,3,4,5,6,7,8,9,10], daq_lidar:[1,2,3,4,5]}\"     # 相机+雷达：时间戳无需对齐\n"
"\n"
"# e.g. begin: rostopic pub -r 1 /daq_ctrl comm_msg/daq_ctrl \"{daq_fusion: 1, daq_hz: 1, daq_camera:[1,2,3,4,5,6,7,8,9,10], daq_lidar:[]}\"              # 相机：时间戳需对齐\n"
"# e.g. begin: rostopic pub -r 1 /daq_ctrl comm_msg/daq_ctrl \"{daq_fusion: 0, daq_hz: 1, daq_camera:[1,2,3,4,5,6,7,8,9,10], daq_lidar:[]}\"              # 相机：时间戳无需对齐\n"
"\n"
"# e.g. begin: rostopic pub -r 1 /daq_ctrl comm_msg/daq_ctrl \"{daq_fusion: 1, daq_hz: 1, daq_camera:[], daq_lidar:[1,2,3,4,5]}\"                         # 雷达：时间戳需对齐\n"
"# e.g. begin: rostopic pub -r 1 /daq_ctrl comm_msg/daq_ctrl \"{daq_fusion: 0, daq_hz: 1, daq_camera:[], daq_lidar:[1,2,3,4,5]}\"                         # 雷达：时间戳无需对齐\n"
"\n"
"# e.g. end:   rostopic pub -r 1 /daq_ctrl comm_msg/daq_ctrl \"{daq_fusion: 1, daq_hz: 1, daq_camera:[], daq_lidar:[]}\"                                  # 结束采集\n"
"# e.g. end:   rostopic pub -r 1 /daq_ctrl comm_msg/daq_ctrl \"{daq_fusion: 0, daq_hz: 1, daq_camera:[], daq_lidar:[]}\"                                  # 结束采集（同上）\n"
"\n"
"bool    daq_fusion      # 采集融合数据（相机+雷达：时间戳对齐）\n"
"uint8   daq_hz          # 采集频率\n"
"uint8[] daq_camera      # 采集相机数据\n"
"uint8[] daq_lidar       # 采集雷达数据\n"
;
  }

  static const char* value(const ::comm_msg::daq_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::daq_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.daq_fusion);
      stream.next(m.daq_hz);
      stream.next(m.daq_camera);
      stream.next(m.daq_lidar);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct daq_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::daq_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::daq_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "daq_fusion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.daq_fusion);
    s << indent << "daq_hz: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.daq_hz);
    s << indent << "daq_camera[]" << std::endl;
    for (size_t i = 0; i < v.daq_camera.size(); ++i)
    {
      s << indent << "  daq_camera[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.daq_camera[i]);
    }
    s << indent << "daq_lidar[]" << std::endl;
    for (size_t i = 0; i < v.daq_lidar.size(); ++i)
    {
      s << indent << "  daq_lidar[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.daq_lidar[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_DAQ_CTRL_H
