// Generated by gencpp from file comm_msg/equipment_info.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_EQUIPMENT_INFO_H
#define COMM_MSG_MESSAGE_EQUIPMENT_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <comm_msg/pose.h>
#include <comm_msg/coor3D.h>
#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct equipment_info_
{
  typedef equipment_info_<ContainerAllocator> Type;

  equipment_info_()
    : status(0)
    , equipmentType(0)
    , QRCodeId(0)
    , QRCodePose()
    , QRCodeOffset()
    , reflectiveStripPosLeft()
    , reflectiveStripPosRight()  {
    }
  equipment_info_(const ContainerAllocator& _alloc)
    : status(0)
    , equipmentType(0)
    , QRCodeId(0)
    , QRCodePose(_alloc)
    , QRCodeOffset(_alloc)
    , reflectiveStripPosLeft(_alloc)
    , reflectiveStripPosRight(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef uint8_t _equipmentType_type;
  _equipmentType_type equipmentType;

   typedef uint32_t _QRCodeId_type;
  _QRCodeId_type QRCodeId;

   typedef  ::comm_msg::pose_<ContainerAllocator>  _QRCodePose_type;
  _QRCodePose_type QRCodePose;

   typedef  ::comm_msg::coor3D_<ContainerAllocator>  _QRCodeOffset_type;
  _QRCodeOffset_type QRCodeOffset;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _reflectiveStripPosLeft_type;
  _reflectiveStripPosLeft_type reflectiveStripPosLeft;

   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _reflectiveStripPosRight_type;
  _reflectiveStripPosRight_type reflectiveStripPosRight;





  typedef boost::shared_ptr< ::comm_msg::equipment_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::equipment_info_<ContainerAllocator> const> ConstPtr;

}; // struct equipment_info_

typedef ::comm_msg::equipment_info_<std::allocator<void> > equipment_info;

typedef boost::shared_ptr< ::comm_msg::equipment_info > equipment_infoPtr;
typedef boost::shared_ptr< ::comm_msg::equipment_info const> equipment_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::equipment_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::equipment_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::equipment_info_<ContainerAllocator1> & lhs, const ::comm_msg::equipment_info_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.equipmentType == rhs.equipmentType &&
    lhs.QRCodeId == rhs.QRCodeId &&
    lhs.QRCodePose == rhs.QRCodePose &&
    lhs.QRCodeOffset == rhs.QRCodeOffset &&
    lhs.reflectiveStripPosLeft == rhs.reflectiveStripPosLeft &&
    lhs.reflectiveStripPosRight == rhs.reflectiveStripPosRight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::equipment_info_<ContainerAllocator1> & lhs, const ::comm_msg::equipment_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::equipment_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::equipment_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::equipment_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::equipment_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::equipment_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::equipment_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::equipment_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8804889ce9395f076bb976f79f9f21b";
  }

  static const char* value(const ::comm_msg::equipment_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8804889ce9395f0ULL;
  static const uint64_t static_value2 = 0x76bb976f79f9f21bULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::equipment_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/equipment_info";
  }

  static const char* value(const ::comm_msg::equipment_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::equipment_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8                   status\n"
"\n"
"# 0是二维码，1是二维码加反光条\n"
"uint8                   equipmentType\n"
"\n"
"uint32                  QRCodeId\n"
"pose                    QRCodePose\n"
"coor3D                  QRCodeOffset\n"
"geometry_msgs/Point32[] reflectiveStripPosLeft\n"
"geometry_msgs/Point32[] reflectiveStripPosRight\n"
"================================================================================\n"
"MSG: comm_msg/pose\n"
"float32 px\n"
"float32 py\n"
"float32 pz\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
"================================================================================\n"
"MSG: comm_msg/coor3D\n"
"float32 pos_x\n"
"float32 pos_y\n"
"float32 pos_z\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::comm_msg::equipment_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::equipment_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.equipmentType);
      stream.next(m.QRCodeId);
      stream.next(m.QRCodePose);
      stream.next(m.QRCodeOffset);
      stream.next(m.reflectiveStripPosLeft);
      stream.next(m.reflectiveStripPosRight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct equipment_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::equipment_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::equipment_info_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "equipmentType: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.equipmentType);
    s << indent << "QRCodeId: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.QRCodeId);
    s << indent << "QRCodePose: ";
    s << std::endl;
    Printer< ::comm_msg::pose_<ContainerAllocator> >::stream(s, indent + "  ", v.QRCodePose);
    s << indent << "QRCodeOffset: ";
    s << std::endl;
    Printer< ::comm_msg::coor3D_<ContainerAllocator> >::stream(s, indent + "  ", v.QRCodeOffset);
    s << indent << "reflectiveStripPosLeft[]" << std::endl;
    for (size_t i = 0; i < v.reflectiveStripPosLeft.size(); ++i)
    {
      s << indent << "  reflectiveStripPosLeft[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.reflectiveStripPosLeft[i]);
    }
    s << indent << "reflectiveStripPosRight[]" << std::endl;
    for (size_t i = 0; i < v.reflectiveStripPosRight.size(); ++i)
    {
      s << indent << "  reflectiveStripPosRight[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.reflectiveStripPosRight[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_EQUIPMENT_INFO_H
