// Generated by gencpp from file comm_msg/label_state.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_LABEL_STATE_H
#define COMM_MSG_MESSAGE_LABEL_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct label_state_
{
  typedef label_state_<ContainerAllocator> Type;

  label_state_()
    : value(0)  {
    }
  label_state_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(NO)
  #undef NO
#endif
#if defined(_WIN32) && defined(YES)
  #undef YES
#endif
#if defined(_WIN32) && defined(MAY)
  #undef MAY
#endif

  enum {
    NO = 0u,
    YES = 1u,
    MAY = 2u,
  };


  typedef boost::shared_ptr< ::comm_msg::label_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::label_state_<ContainerAllocator> const> ConstPtr;

}; // struct label_state_

typedef ::comm_msg::label_state_<std::allocator<void> > label_state;

typedef boost::shared_ptr< ::comm_msg::label_state > label_statePtr;
typedef boost::shared_ptr< ::comm_msg::label_state const> label_stateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::label_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::label_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::label_state_<ContainerAllocator1> & lhs, const ::comm_msg::label_state_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::label_state_<ContainerAllocator1> & lhs, const ::comm_msg::label_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::label_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::label_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::label_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::label_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::label_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::label_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::label_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "888716ada627b9e5d6021e226a28f209";
  }

  static const char* value(const ::comm_msg::label_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x888716ada627b9e5ULL;
  static const uint64_t static_value2 = 0xd6021e226a28f209ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::label_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/label_state";
  }

  static const char* value(const ::comm_msg::label_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::label_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Note: 标签类别存在状态\n"
"\n"
"uint8 NO  = 0\n"
"uint8 YES = 1\n"
"uint8 MAY = 2\n"
"\n"
"uint8 value\n"
;
  }

  static const char* value(const ::comm_msg::label_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::label_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct label_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::label_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::label_state_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_LABEL_STATE_H
