// Generated by gencpp from file comm_msg/locationInfo3D.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_LOCATIONINFO3D_H
#define COMM_MSG_MESSAGE_LOCATIONINFO3D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct locationInfo3D_
{
  typedef locationInfo3D_<ContainerAllocator> Type;

  locationInfo3D_()
    : header()
    , status(0)
    , subMapNo(0)
    , posX(0.0)
    , posY(0.0)
    , posZ(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  locationInfo3D_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , status(0)
    , subMapNo(0)
    , posX(0.0)
    , posY(0.0)
    , posZ(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _status_type;
  _status_type status;

   typedef int32_t _subMapNo_type;
  _subMapNo_type subMapNo;

   typedef float _posX_type;
  _posX_type posX;

   typedef float _posY_type;
  _posY_type posY;

   typedef float _posZ_type;
  _posZ_type posZ;

   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::comm_msg::locationInfo3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::locationInfo3D_<ContainerAllocator> const> ConstPtr;

}; // struct locationInfo3D_

typedef ::comm_msg::locationInfo3D_<std::allocator<void> > locationInfo3D;

typedef boost::shared_ptr< ::comm_msg::locationInfo3D > locationInfo3DPtr;
typedef boost::shared_ptr< ::comm_msg::locationInfo3D const> locationInfo3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::locationInfo3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::locationInfo3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::locationInfo3D_<ContainerAllocator1> & lhs, const ::comm_msg::locationInfo3D_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.status == rhs.status &&
    lhs.subMapNo == rhs.subMapNo &&
    lhs.posX == rhs.posX &&
    lhs.posY == rhs.posY &&
    lhs.posZ == rhs.posZ &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::locationInfo3D_<ContainerAllocator1> & lhs, const ::comm_msg::locationInfo3D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::locationInfo3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::locationInfo3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::locationInfo3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::locationInfo3D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::locationInfo3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::locationInfo3D_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::locationInfo3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9467975d89bc17ef59573b6ebcb142d";
  }

  static const char* value(const ::comm_msg::locationInfo3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9467975d89bc17eULL;
  static const uint64_t static_value2 = 0xf59573b6ebcb142dULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::locationInfo3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/locationInfo3D";
  }

  static const char* value(const ::comm_msg::locationInfo3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::locationInfo3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# location status, refer to MAP_NODE_STATE_ENUM\n"
"Header header\n"
"int32 status\n"
"\n"
"# sub map no, this is valid when >= 0, if -ing status, this is the new sub map no\n"
"int32 subMapNo\n"
"\n"
"# Comb Map pose, which is valid When status is > 0.\n"
"float32 posX\n"
"float32 posY\n"
"float32 posZ\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::comm_msg::locationInfo3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::locationInfo3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.status);
      stream.next(m.subMapNo);
      stream.next(m.posX);
      stream.next(m.posY);
      stream.next(m.posZ);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct locationInfo3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::locationInfo3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::locationInfo3D_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "subMapNo: ";
    Printer<int32_t>::stream(s, indent + "  ", v.subMapNo);
    s << indent << "posX: ";
    Printer<float>::stream(s, indent + "  ", v.posX);
    s << indent << "posY: ";
    Printer<float>::stream(s, indent + "  ", v.posY);
    s << indent << "posZ: ";
    Printer<float>::stream(s, indent + "  ", v.posZ);
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_LOCATIONINFO3D_H
