// Generated by gencpp from file comm_msg/mapping_ctrl.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_MAPPING_CTRL_H
#define COMM_MSG_MESSAGE_MAPPING_CTRL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct mapping_ctrl_
{
  typedef mapping_ctrl_<ContainerAllocator> Type;

  mapping_ctrl_()
    : cmd(0)  {
    }
  mapping_ctrl_(const ContainerAllocator& _alloc)
    : cmd(0)  {
  (void)_alloc;
    }



   typedef int32_t _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::comm_msg::mapping_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::mapping_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct mapping_ctrl_

typedef ::comm_msg::mapping_ctrl_<std::allocator<void> > mapping_ctrl;

typedef boost::shared_ptr< ::comm_msg::mapping_ctrl > mapping_ctrlPtr;
typedef boost::shared_ptr< ::comm_msg::mapping_ctrl const> mapping_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::mapping_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::mapping_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::mapping_ctrl_<ContainerAllocator1> & lhs, const ::comm_msg::mapping_ctrl_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::mapping_ctrl_<ContainerAllocator1> & lhs, const ::comm_msg::mapping_ctrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::mapping_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::mapping_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::mapping_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::mapping_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::mapping_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::mapping_ctrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::mapping_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66990e73c7aab0c47ddcdc70f7fa5bd0";
  }

  static const char* value(const ::comm_msg::mapping_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66990e73c7aab0c4ULL;
  static const uint64_t static_value2 = 0x7ddcdc70f7fa5bd0ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::mapping_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/mapping_ctrl";
  }

  static const char* value(const ::comm_msg::mapping_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::mapping_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cmd #1:save map command 2:enable gnss 3:disable gnss\n"
;
  }

  static const char* value(const ::comm_msg::mapping_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::mapping_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mapping_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::mapping_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::mapping_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_MAPPING_CTRL_H
