// Generated by gencpp from file comm_msg/move_ctrl.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_MOVE_CTRL_H
#define COMM_MSG_MESSAGE_MOVE_CTRL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct move_ctrl_
{
  typedef move_ctrl_<ContainerAllocator> Type;

  move_ctrl_()
    : header()
    , isExistTask(0)
    , isTeleCtrl(0)
    , isCleaning(0)
    , steeringAngle(0.0)
    , moveLinearVel(0.0)
    , isMoveSmooth(0)
    , isStopSmooth(0)
    , isUseSecurityRedundancy(0)
    , isIgnoreLaserData(0)
    , isIgnoreUltrasonicData(0)
    , planningModel(0)
    , brushModel(0)  {
    }
  move_ctrl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , isExistTask(0)
    , isTeleCtrl(0)
    , isCleaning(0)
    , steeringAngle(0.0)
    , moveLinearVel(0.0)
    , isMoveSmooth(0)
    , isStopSmooth(0)
    , isUseSecurityRedundancy(0)
    , isIgnoreLaserData(0)
    , isIgnoreUltrasonicData(0)
    , planningModel(0)
    , brushModel(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _isExistTask_type;
  _isExistTask_type isExistTask;

   typedef uint8_t _isTeleCtrl_type;
  _isTeleCtrl_type isTeleCtrl;

   typedef uint8_t _isCleaning_type;
  _isCleaning_type isCleaning;

   typedef float _steeringAngle_type;
  _steeringAngle_type steeringAngle;

   typedef float _moveLinearVel_type;
  _moveLinearVel_type moveLinearVel;

   typedef uint8_t _isMoveSmooth_type;
  _isMoveSmooth_type isMoveSmooth;

   typedef uint8_t _isStopSmooth_type;
  _isStopSmooth_type isStopSmooth;

   typedef uint8_t _isUseSecurityRedundancy_type;
  _isUseSecurityRedundancy_type isUseSecurityRedundancy;

   typedef uint8_t _isIgnoreLaserData_type;
  _isIgnoreLaserData_type isIgnoreLaserData;

   typedef uint8_t _isIgnoreUltrasonicData_type;
  _isIgnoreUltrasonicData_type isIgnoreUltrasonicData;

   typedef uint8_t _planningModel_type;
  _planningModel_type planningModel;

   typedef uint8_t _brushModel_type;
  _brushModel_type brushModel;





  typedef boost::shared_ptr< ::comm_msg::move_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::move_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct move_ctrl_

typedef ::comm_msg::move_ctrl_<std::allocator<void> > move_ctrl;

typedef boost::shared_ptr< ::comm_msg::move_ctrl > move_ctrlPtr;
typedef boost::shared_ptr< ::comm_msg::move_ctrl const> move_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::move_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::move_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::move_ctrl_<ContainerAllocator1> & lhs, const ::comm_msg::move_ctrl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.isExistTask == rhs.isExistTask &&
    lhs.isTeleCtrl == rhs.isTeleCtrl &&
    lhs.isCleaning == rhs.isCleaning &&
    lhs.steeringAngle == rhs.steeringAngle &&
    lhs.moveLinearVel == rhs.moveLinearVel &&
    lhs.isMoveSmooth == rhs.isMoveSmooth &&
    lhs.isStopSmooth == rhs.isStopSmooth &&
    lhs.isUseSecurityRedundancy == rhs.isUseSecurityRedundancy &&
    lhs.isIgnoreLaserData == rhs.isIgnoreLaserData &&
    lhs.isIgnoreUltrasonicData == rhs.isIgnoreUltrasonicData &&
    lhs.planningModel == rhs.planningModel &&
    lhs.brushModel == rhs.brushModel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::move_ctrl_<ContainerAllocator1> & lhs, const ::comm_msg::move_ctrl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::move_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::move_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::move_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::move_ctrl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::move_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::move_ctrl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::move_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50e3072a553418d33ffdbff20878da88";
  }

  static const char* value(const ::comm_msg::move_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50e3072a553418d3ULL;
  static const uint64_t static_value2 = 0x3ffdbff20878da88ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::move_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/move_ctrl";
  }

  static const char* value(const ::comm_msg::move_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::move_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n"
"\n"
"uint8   isExistTask\n"
"uint8   isTeleCtrl\n"
"uint8   isCleaning\n"
"float32 steeringAngle\n"
"float32 moveLinearVel\n"
"uint8   isMoveSmooth\n"
"uint8   isStopSmooth\n"
"\n"
"# 发给安全冗余模块新增的消息\n"
"uint8   isUseSecurityRedundancy\n"
"uint8   isIgnoreLaserData\n"
"uint8   isIgnoreUltrasonicData\n"
"uint8   planningModel          # 0无效模式, 1贴边模式, 2跟线模式, 3发点远程遥控模式, 4方向远程遥控模式, 5调试工具遥控车辆\n"
"uint8   brushModel             # 0关刷模式，1开刷模式\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::comm_msg::move_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::move_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.isExistTask);
      stream.next(m.isTeleCtrl);
      stream.next(m.isCleaning);
      stream.next(m.steeringAngle);
      stream.next(m.moveLinearVel);
      stream.next(m.isMoveSmooth);
      stream.next(m.isStopSmooth);
      stream.next(m.isUseSecurityRedundancy);
      stream.next(m.isIgnoreLaserData);
      stream.next(m.isIgnoreUltrasonicData);
      stream.next(m.planningModel);
      stream.next(m.brushModel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::move_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::move_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "isExistTask: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isExistTask);
    s << indent << "isTeleCtrl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isTeleCtrl);
    s << indent << "isCleaning: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isCleaning);
    s << indent << "steeringAngle: ";
    Printer<float>::stream(s, indent + "  ", v.steeringAngle);
    s << indent << "moveLinearVel: ";
    Printer<float>::stream(s, indent + "  ", v.moveLinearVel);
    s << indent << "isMoveSmooth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isMoveSmooth);
    s << indent << "isStopSmooth: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isStopSmooth);
    s << indent << "isUseSecurityRedundancy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isUseSecurityRedundancy);
    s << indent << "isIgnoreLaserData: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isIgnoreLaserData);
    s << indent << "isIgnoreUltrasonicData: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isIgnoreUltrasonicData);
    s << indent << "planningModel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.planningModel);
    s << indent << "brushModel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brushModel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_MOVE_CTRL_H
