// Generated by gencpp from file comm_msg/pose_score.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_POSE_SCORE_H
#define COMM_MSG_MESSAGE_POSE_SCORE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <comm_msg/pose3D.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct pose_score_
{
  typedef pose_score_<ContainerAllocator> Type;

  pose_score_()
    : score(0.0)
    , pose()  {
    }
  pose_score_(const ContainerAllocator& _alloc)
    : score(0.0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef float _score_type;
  _score_type score;

   typedef  ::comm_msg::pose3D_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::comm_msg::pose_score_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::pose_score_<ContainerAllocator> const> ConstPtr;

}; // struct pose_score_

typedef ::comm_msg::pose_score_<std::allocator<void> > pose_score;

typedef boost::shared_ptr< ::comm_msg::pose_score > pose_scorePtr;
typedef boost::shared_ptr< ::comm_msg::pose_score const> pose_scoreConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::pose_score_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::pose_score_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::pose_score_<ContainerAllocator1> & lhs, const ::comm_msg::pose_score_<ContainerAllocator2> & rhs)
{
  return lhs.score == rhs.score &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::pose_score_<ContainerAllocator1> & lhs, const ::comm_msg::pose_score_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::pose_score_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::pose_score_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::pose_score_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::pose_score_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::pose_score_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::pose_score_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::pose_score_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ba278e321050d4e0b42ab7a7a69fe0c";
  }

  static const char* value(const ::comm_msg::pose_score_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ba278e321050d4eULL;
  static const uint64_t static_value2 = 0x0b42ab7a7a69fe0cULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::pose_score_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/pose_score";
  }

  static const char* value(const ::comm_msg::pose_score_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::pose_score_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 score\n"
"pose3D  pose\n"
"================================================================================\n"
"MSG: comm_msg/pose3D\n"
"float32 posX\n"
"float32 posY\n"
"float32 posZ\n"
"float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::comm_msg::pose_score_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::pose_score_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.score);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_score_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::pose_score_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::pose_score_<ContainerAllocator>& v)
  {
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::comm_msg::pose3D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_POSE_SCORE_H
