// Generated by gencpp from file comm_msg/qrcode_pose.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_QRCODE_POSE_H
#define COMM_MSG_MESSAGE_QRCODE_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct qrcode_pose_
{
  typedef qrcode_pose_<ContainerAllocator> Type;

  qrcode_pose_()
    : header()
    , id(0)
    , pose()  {
    }
  qrcode_pose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::comm_msg::qrcode_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::qrcode_pose_<ContainerAllocator> const> ConstPtr;

}; // struct qrcode_pose_

typedef ::comm_msg::qrcode_pose_<std::allocator<void> > qrcode_pose;

typedef boost::shared_ptr< ::comm_msg::qrcode_pose > qrcode_posePtr;
typedef boost::shared_ptr< ::comm_msg::qrcode_pose const> qrcode_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::qrcode_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::qrcode_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::qrcode_pose_<ContainerAllocator1> & lhs, const ::comm_msg::qrcode_pose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::qrcode_pose_<ContainerAllocator1> & lhs, const ::comm_msg::qrcode_pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::qrcode_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::qrcode_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::qrcode_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::qrcode_pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::qrcode_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::qrcode_pose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::qrcode_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7959a9b3fd2053f3de440accefb2edd4";
  }

  static const char* value(const ::comm_msg::qrcode_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7959a9b3fd2053f3ULL;
  static const uint64_t static_value2 = 0xde440accefb2edd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::qrcode_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/qrcode_pose";
  }

  static const char* value(const ::comm_msg::qrcode_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::qrcode_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header              header\n"
"int32               id\n"
"geometry_msgs/Pose  pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::comm_msg::qrcode_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::qrcode_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct qrcode_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::qrcode_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::qrcode_pose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_QRCODE_POSE_H
