// Generated by gencpp from file comm_msg/radarTarget.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_RADARTARGET_H
#define COMM_MSG_MESSAGE_RADARTARGET_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct radarTarget_
{
  typedef radarTarget_<ContainerAllocator> Type;

  radarTarget_()
    : targetDistx(0.0)
    , targetDisty(0.0)
    , targetVelx(0.0)
    , targetVely(0.0)  {
    }
  radarTarget_(const ContainerAllocator& _alloc)
    : targetDistx(0.0)
    , targetDisty(0.0)
    , targetVelx(0.0)
    , targetVely(0.0)  {
  (void)_alloc;
    }



   typedef float _targetDistx_type;
  _targetDistx_type targetDistx;

   typedef float _targetDisty_type;
  _targetDisty_type targetDisty;

   typedef float _targetVelx_type;
  _targetVelx_type targetVelx;

   typedef float _targetVely_type;
  _targetVely_type targetVely;





  typedef boost::shared_ptr< ::comm_msg::radarTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::radarTarget_<ContainerAllocator> const> ConstPtr;

}; // struct radarTarget_

typedef ::comm_msg::radarTarget_<std::allocator<void> > radarTarget;

typedef boost::shared_ptr< ::comm_msg::radarTarget > radarTargetPtr;
typedef boost::shared_ptr< ::comm_msg::radarTarget const> radarTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::radarTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::radarTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::radarTarget_<ContainerAllocator1> & lhs, const ::comm_msg::radarTarget_<ContainerAllocator2> & rhs)
{
  return lhs.targetDistx == rhs.targetDistx &&
    lhs.targetDisty == rhs.targetDisty &&
    lhs.targetVelx == rhs.targetVelx &&
    lhs.targetVely == rhs.targetVely;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::radarTarget_<ContainerAllocator1> & lhs, const ::comm_msg::radarTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::radarTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::radarTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::radarTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::radarTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::radarTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::radarTarget_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::radarTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f0ce27dc024af9302b335afb3187795";
  }

  static const char* value(const ::comm_msg::radarTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f0ce27dc024af93ULL;
  static const uint64_t static_value2 = 0x02b335afb3187795ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::radarTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/radarTarget";
  }

  static const char* value(const ::comm_msg::radarTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::radarTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32   targetDistx         # 目标相对于清扫车参考坐标系X轴坐标\n"
"float32   targetDisty         # 目标相对于清扫车参考坐标系Y轴坐标\n"
"float32   targetVelx          # 目标相对于清扫车参考坐标系X轴速度\n"
"float32   targetVely          # 目标相对于清扫车参考坐标系Y轴速度\n"
;
  }

  static const char* value(const ::comm_msg::radarTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::radarTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targetDistx);
      stream.next(m.targetDisty);
      stream.next(m.targetVelx);
      stream.next(m.targetVely);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radarTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::radarTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::radarTarget_<ContainerAllocator>& v)
  {
    s << indent << "targetDistx: ";
    Printer<float>::stream(s, indent + "  ", v.targetDistx);
    s << indent << "targetDisty: ";
    Printer<float>::stream(s, indent + "  ", v.targetDisty);
    s << indent << "targetVelx: ";
    Printer<float>::stream(s, indent + "  ", v.targetVelx);
    s << indent << "targetVely: ";
    Printer<float>::stream(s, indent + "  ", v.targetVely);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_RADARTARGET_H
