// Generated by gencpp from file comm_msg/spoiler_detect.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_SPOILER_DETECT_H
#define COMM_MSG_MESSAGE_SPOILER_DETECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <comm_msg/label.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct spoiler_detect_
{
  typedef spoiler_detect_<ContainerAllocator> Type;

  spoiler_detect_()
    : header()
    , label()
    , detect_value(0)  {
    }
  spoiler_detect_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , label(_alloc)
    , detect_value(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::comm_msg::label_<ContainerAllocator>  _label_type;
  _label_type label;

   typedef uint8_t _detect_value_type;
  _detect_value_type detect_value;





  typedef boost::shared_ptr< ::comm_msg::spoiler_detect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::spoiler_detect_<ContainerAllocator> const> ConstPtr;

}; // struct spoiler_detect_

typedef ::comm_msg::spoiler_detect_<std::allocator<void> > spoiler_detect;

typedef boost::shared_ptr< ::comm_msg::spoiler_detect > spoiler_detectPtr;
typedef boost::shared_ptr< ::comm_msg::spoiler_detect const> spoiler_detectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::spoiler_detect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::spoiler_detect_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::spoiler_detect_<ContainerAllocator1> & lhs, const ::comm_msg::spoiler_detect_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.label == rhs.label &&
    lhs.detect_value == rhs.detect_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::spoiler_detect_<ContainerAllocator1> & lhs, const ::comm_msg::spoiler_detect_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::spoiler_detect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::spoiler_detect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::spoiler_detect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::spoiler_detect_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::spoiler_detect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::spoiler_detect_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::spoiler_detect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03ce56ab1e5a7e206499aa32ad624a78";
  }

  static const char* value(const ::comm_msg::spoiler_detect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03ce56ab1e5a7e20ULL;
  static const uint64_t static_value2 = 0x6499aa32ad624a78ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::spoiler_detect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/spoiler_detect";
  }

  static const char* value(const ::comm_msg::spoiler_detect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::spoiler_detect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"label label         # 检测到的尾翼范围内障碍物类别\n"
"uint8 detect_value  # 检测到尾翼范围内是障碍物存在  0: no, 1: yes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: comm_msg/label\n"
"#Note: 枚举类别、枚举值、枚举顺序均不可随意改动，不然md5不匹配，消息将无法正常解析\n"
"\n"
"uint8 UNKNOWN                   = 0     #未知（统一类别）\n"
"uint8 PEDESTRIAN                = 1     #行人\n"
"uint8 CYCLIST                   = 2     #骑自行车的人\n"
"uint8 BICYCLE                   = 3     #自行车（两轮车）\n"
"uint8 CAR                       = 4     #汽车\n"
"uint8 TRUCK                     = 5     #卡车\n"
"uint8 TRAM                      = 6     #有轨电车\n"
"uint8 TRICYCLE                  = 7     #三轮车\n"
"uint8 BUS                       = 8     #公交车\n"
"\n"
"uint8 LOWOBST                   = 10    #低矮障碍\n"
"uint8 ROADEDGE                  = 11    #道路边缘\n"
"uint8 PIPELINE                  = 12    #水管管线\n"
"uint8 CORDON                    = 13    #警戒线\n"
"uint8 TREELAWN                  = 14    #街道绿化带\n"
"uint8 THICKPIPE                 = 15    #粗水管\n"
"uint8 CORD                      = 16    #电线、缆绳\n"
"uint8 SLOPE_PAD                 = 17    #斜坡垫\n"
"uint8 SPEED_BUMP                = 18    #减速带\n"
"\n"
"uint8 COVER_SOLID               = 20    #实心井盖\n"
"uint8 COVER_HOLLOW              = 21    #栅格井盖\n"
"uint8 TRAFFIC_CONE              = 22    #雪糕筒（交通锥）\n"
"uint8 METAL_BARRIER             = 23    #金属围栏（铁马）\n"
"uint8 MEDIAN_BARRIER            = 24    #栅栏（道路中央隔离带）\n"
"uint8 CEREMONIAL_POLE           = 25    #礼宾杆\n"
"uint8 BOLLARD                   = 26    #路桩\n"
"\n"
"uint8 GARBAGE                   = 40    #垃圾（统称）\n"
"uint8 GARBAGE_BOTTLE            = 41    #瓶子\n"
"uint8 GARBAGE_PAPER             = 42    #纸巾\n"
"uint8 GARBAGE_BRANCH            = 43    #树枝\n"
"uint8 GARBAGE_LEAVES            = 44    #树叶\n"
"uint8 GARBAGE_BOUGH             = 45    #粗树枝、长树枝\n"
"uint8 GARBAGE_CUP               = 46    #奶茶杯\n"
"uint8 GARBAGE_CAN               = 47    #易拉罐\n"
"uint8 GARBAGE_CARTON            = 48    #纸盒\n"
"uint8 GARBAGE_PACKAGE           = 49    #烟盒\n"
"uint8 GARBAGE_BRICK             = 70    #砖块（小砖块）\n"
"uint8 GARBAGE_CIGARETTEEND      = 71    #烟头\n"
"\n"
"\n"
"uint8 TRAFFIC_LIGHT             = 50    #交通灯（统称）\n"
"uint8 TRAFFIC_LIGHT_OFF         = 51    #交通灯-关闭\n"
"uint8 TRAFFIC_LIGHT_RED         = 52    #交通灯-红灯\n"
"uint8 TRAFFIC_LIGHT_GREEN       = 53    #交通灯-绿灯\n"
"uint8 TRAFFIC_LIGHT_YELLOW      = 54    #交通灯-黄灯\n"
"\n"
"uint8 TRAFFIC_LIGHT_GROUP       = 55    #交通灯-灯组\n"
"uint8 TRAFFIC_LIGHT_OFF_LITE    = 56    #交通灯-关闭（小灯）\n"
"uint8 TRAFFIC_LIGHT_RED_LITE    = 57    #交通灯-红灯（小灯）\n"
"uint8 TRAFFIC_LIGHT_GREEN_LITE  = 58    #交通灯-绿灯（小灯）\n"
"uint8 TRAFFIC_LIGHT_YELLOW_LITE = 59    #交通灯-黄灯（小灯）\n"
"\n"
"uint8 CHARGING_GUN              = 60    #充电枪\n"
"\n"
"uint8 PLACEHOLDER               = 101    #占位符(MAX)\n"
"\n"
"uint8 value\n"
;
  }

  static const char* value(const ::comm_msg::spoiler_detect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::spoiler_detect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.label);
      stream.next(m.detect_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct spoiler_detect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::spoiler_detect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::spoiler_detect_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "label: ";
    s << std::endl;
    Printer< ::comm_msg::label_<ContainerAllocator> >::stream(s, indent + "  ", v.label);
    s << indent << "detect_value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detect_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_SPOILER_DETECT_H
