// Generated by gencpp from file comm_msg/traffic_light_info.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_TRAFFIC_LIGHT_INFO_H
#define COMM_MSG_MESSAGE_TRAFFIC_LIGHT_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct traffic_light_info_
{
  typedef traffic_light_info_<ContainerAllocator> Type;

  traffic_light_info_()
    : type(0)
    , pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)
    , row_length(0.0)
    , col_length(0.0)  {
    }
  traffic_light_info_(const ContainerAllocator& _alloc)
    : type(0)
    , pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)
    , row_length(0.0)
    , col_length(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;

   typedef float _pos_z_type;
  _pos_z_type pos_z;

   typedef float _row_length_type;
  _row_length_type row_length;

   typedef float _col_length_type;
  _col_length_type col_length;





  typedef boost::shared_ptr< ::comm_msg::traffic_light_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::traffic_light_info_<ContainerAllocator> const> ConstPtr;

}; // struct traffic_light_info_

typedef ::comm_msg::traffic_light_info_<std::allocator<void> > traffic_light_info;

typedef boost::shared_ptr< ::comm_msg::traffic_light_info > traffic_light_infoPtr;
typedef boost::shared_ptr< ::comm_msg::traffic_light_info const> traffic_light_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::traffic_light_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::traffic_light_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::traffic_light_info_<ContainerAllocator1> & lhs, const ::comm_msg::traffic_light_info_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.pos_z == rhs.pos_z &&
    lhs.row_length == rhs.row_length &&
    lhs.col_length == rhs.col_length;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::traffic_light_info_<ContainerAllocator1> & lhs, const ::comm_msg::traffic_light_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::traffic_light_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::traffic_light_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::traffic_light_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::traffic_light_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::traffic_light_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::traffic_light_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::traffic_light_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4755f326c42173c8ecd115dcd1f1001";
  }

  static const char* value(const ::comm_msg::traffic_light_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4755f326c42173cULL;
  static const uint64_t static_value2 = 0x8ecd115dcd1f1001ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::traffic_light_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/traffic_light_info";
  }

  static const char* value(const ::comm_msg::traffic_light_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::traffic_light_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8    type           # 交通灯显示类型：1(读秒类型) 2(频闪类型) 3(高频亮灭型)\n"
"float32  pos_x          # 交通灯中在地图上的坐标x\n"
"float32  pos_y          # 交通灯中在地图上的坐标y\n"
"float32  pos_z          # 交通灯中在地图上的坐标z\n"
"float32  row_length     # 交通灯横向长度\n"
"float32  col_length     # 交通灯纵向长度\n"
;
  }

  static const char* value(const ::comm_msg::traffic_light_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::traffic_light_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.pos_z);
      stream.next(m.row_length);
      stream.next(m.col_length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct traffic_light_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::traffic_light_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::traffic_light_info_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
    s << indent << "pos_z: ";
    Printer<float>::stream(s, indent + "  ", v.pos_z);
    s << indent << "row_length: ";
    Printer<float>::stream(s, indent + "  ", v.row_length);
    s << indent << "col_length: ";
    Printer<float>::stream(s, indent + "  ", v.col_length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_TRAFFIC_LIGHT_INFO_H
