// Generated by gencpp from file comm_msg/trash_box_obst_state.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_TRASH_BOX_OBST_STATE_H
#define COMM_MSG_MESSAGE_TRASH_BOX_OBST_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_msg
{
template <class ContainerAllocator>
struct trash_box_obst_state_
{
  typedef trash_box_obst_state_<ContainerAllocator> Type;

  trash_box_obst_state_()
    : exisitObstUp(false)
    , exisitObstDown(false)  {
    }
  trash_box_obst_state_(const ContainerAllocator& _alloc)
    : exisitObstUp(false)
    , exisitObstDown(false)  {
  (void)_alloc;
    }



   typedef uint8_t _exisitObstUp_type;
  _exisitObstUp_type exisitObstUp;

   typedef uint8_t _exisitObstDown_type;
  _exisitObstDown_type exisitObstDown;





  typedef boost::shared_ptr< ::comm_msg::trash_box_obst_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::trash_box_obst_state_<ContainerAllocator> const> ConstPtr;

}; // struct trash_box_obst_state_

typedef ::comm_msg::trash_box_obst_state_<std::allocator<void> > trash_box_obst_state;

typedef boost::shared_ptr< ::comm_msg::trash_box_obst_state > trash_box_obst_statePtr;
typedef boost::shared_ptr< ::comm_msg::trash_box_obst_state const> trash_box_obst_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::trash_box_obst_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::trash_box_obst_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::trash_box_obst_state_<ContainerAllocator1> & lhs, const ::comm_msg::trash_box_obst_state_<ContainerAllocator2> & rhs)
{
  return lhs.exisitObstUp == rhs.exisitObstUp &&
    lhs.exisitObstDown == rhs.exisitObstDown;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::trash_box_obst_state_<ContainerAllocator1> & lhs, const ::comm_msg::trash_box_obst_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::trash_box_obst_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::trash_box_obst_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::trash_box_obst_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::trash_box_obst_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::trash_box_obst_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::trash_box_obst_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::trash_box_obst_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "051ec62ff947ba3d46f50bc3f41f117f";
  }

  static const char* value(const ::comm_msg::trash_box_obst_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x051ec62ff947ba3dULL;
  static const uint64_t static_value2 = 0x46f50bc3f41f117fULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::trash_box_obst_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/trash_box_obst_state";
  }

  static const char* value(const ::comm_msg::trash_box_obst_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::trash_box_obst_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# trash box obst state\n"
"bool  exisitObstUp        #  垃圾箱抬升方向是否有障碍\n"
"bool  exisitObstDown      #  垃圾箱回收方向是否有障碍\n"
;
  }

  static const char* value(const ::comm_msg::trash_box_obst_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::trash_box_obst_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.exisitObstUp);
      stream.next(m.exisitObstDown);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct trash_box_obst_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::trash_box_obst_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::trash_box_obst_state_<ContainerAllocator>& v)
  {
    s << indent << "exisitObstUp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.exisitObstUp);
    s << indent << "exisitObstDown: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.exisitObstDown);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_TRASH_BOX_OBST_STATE_H
