// Generated by gencpp from file comm_msg/ultrasonicsData.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_ULTRASONICSDATA_H
#define COMM_MSG_MESSAGE_ULTRASONICSDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <comm_msg/ultrasonicData.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct ultrasonicsData_
{
  typedef ultrasonicsData_<ContainerAllocator> Type;

  ultrasonicsData_()
    : header()
    , usData()  {
    }
  ultrasonicsData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , usData(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::comm_msg::ultrasonicData_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_msg::ultrasonicData_<ContainerAllocator> >> _usData_type;
  _usData_type usData;





  typedef boost::shared_ptr< ::comm_msg::ultrasonicsData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::ultrasonicsData_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasonicsData_

typedef ::comm_msg::ultrasonicsData_<std::allocator<void> > ultrasonicsData;

typedef boost::shared_ptr< ::comm_msg::ultrasonicsData > ultrasonicsDataPtr;
typedef boost::shared_ptr< ::comm_msg::ultrasonicsData const> ultrasonicsDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::ultrasonicsData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::ultrasonicsData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::ultrasonicsData_<ContainerAllocator1> & lhs, const ::comm_msg::ultrasonicsData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.usData == rhs.usData;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::ultrasonicsData_<ContainerAllocator1> & lhs, const ::comm_msg::ultrasonicsData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::ultrasonicsData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::ultrasonicsData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::ultrasonicsData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::ultrasonicsData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::ultrasonicsData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::ultrasonicsData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::ultrasonicsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "107cce378ac5b6b859f4402e5340a53f";
  }

  static const char* value(const ::comm_msg::ultrasonicsData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x107cce378ac5b6b8ULL;
  static const uint64_t static_value2 = 0x59f4402e5340a53fULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::ultrasonicsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/ultrasonicsData";
  }

  static const char* value(const ::comm_msg::ultrasonicsData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::ultrasonicsData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header           header\n"
"ultrasonicData[] usData\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: comm_msg/ultrasonicData\n"
"string   usName\n"
"coor2D[] data\n"
"================================================================================\n"
"MSG: comm_msg/coor2D\n"
"coorLabel   label       #坐标类别\n"
"float32     pos_x\n"
"float32     pos_y\n"
"================================================================================\n"
"MSG: comm_msg/coorLabel\n"
"uint8   UNKNOWN      = 0  #未知\n"
"uint8   STATIC       = 1  #静态\n"
"uint8   DYNAMIC      = 2  #动态\n"
"uint8   HOLLOW_OBST  = 3  #空洞障碍\n"
"uint8   SHORT_HOLD   = 4  #低矮维持\n"
"uint8   COMMON_HOLD  = 5  #常规维持\n"
"uint8   BLIND_SPOT   = 6  #盲区障碍\n"
"uint8   SLOPE_PAD    = 7  #斜坡垫\n"
"uint8   CONTACT_EDGE = 8  #触边障碍\n"
"uint8   TREELAWN     = 9  #绿植障碍\n"
"uint8   ULTRASONIC   = 10 #超声\n"
"\n"
"uint8 value\n"
;
  }

  static const char* value(const ::comm_msg::ultrasonicsData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::ultrasonicsData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.usData);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultrasonicsData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::ultrasonicsData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::ultrasonicsData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "usData[]" << std::endl;
    for (size_t i = 0; i < v.usData.size(); ++i)
    {
      s << indent << "  usData[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_msg::ultrasonicData_<ContainerAllocator> >::stream(s, indent + "    ", v.usData[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_ULTRASONICSDATA_H
