// Generated by gencpp from file comm_msg/ultrasonicData.msg
// DO NOT EDIT!


#ifndef COMM_MSG_MESSAGE_ULTRASONICDATA_H
#define COMM_MSG_MESSAGE_ULTRASONICDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <comm_msg/coor2D.h>

namespace comm_msg
{
template <class ContainerAllocator>
struct ultrasonicData_
{
  typedef ultrasonicData_<ContainerAllocator> Type;

  ultrasonicData_()
    : usName()
    , data()  {
    }
  ultrasonicData_(const ContainerAllocator& _alloc)
    : usName(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _usName_type;
  _usName_type usName;

   typedef std::vector< ::comm_msg::coor2D_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::comm_msg::coor2D_<ContainerAllocator> >> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::comm_msg::ultrasonicData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_msg::ultrasonicData_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasonicData_

typedef ::comm_msg::ultrasonicData_<std::allocator<void> > ultrasonicData;

typedef boost::shared_ptr< ::comm_msg::ultrasonicData > ultrasonicDataPtr;
typedef boost::shared_ptr< ::comm_msg::ultrasonicData const> ultrasonicDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_msg::ultrasonicData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_msg::ultrasonicData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_msg::ultrasonicData_<ContainerAllocator1> & lhs, const ::comm_msg::ultrasonicData_<ContainerAllocator2> & rhs)
{
  return lhs.usName == rhs.usName &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_msg::ultrasonicData_<ContainerAllocator1> & lhs, const ::comm_msg::ultrasonicData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_msg::ultrasonicData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_msg::ultrasonicData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::ultrasonicData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_msg::ultrasonicData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::ultrasonicData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_msg::ultrasonicData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_msg::ultrasonicData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16d3d45049c1ab8e0a2113ea61e36760";
  }

  static const char* value(const ::comm_msg::ultrasonicData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16d3d45049c1ab8eULL;
  static const uint64_t static_value2 = 0x0a2113ea61e36760ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_msg::ultrasonicData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_msg/ultrasonicData";
  }

  static const char* value(const ::comm_msg::ultrasonicData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_msg::ultrasonicData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string   usName\n"
"coor2D[] data\n"
"================================================================================\n"
"MSG: comm_msg/coor2D\n"
"coorLabel   label       #坐标类别\n"
"float32     pos_x\n"
"float32     pos_y\n"
"================================================================================\n"
"MSG: comm_msg/coorLabel\n"
"uint8   UNKNOWN      = 0  #未知\n"
"uint8   STATIC       = 1  #静态\n"
"uint8   DYNAMIC      = 2  #动态\n"
"uint8   HOLLOW_OBST  = 3  #空洞障碍\n"
"uint8   SHORT_HOLD   = 4  #低矮维持\n"
"uint8   COMMON_HOLD  = 5  #常规维持\n"
"uint8   BLIND_SPOT   = 6  #盲区障碍\n"
"uint8   SLOPE_PAD    = 7  #斜坡垫\n"
"uint8   CONTACT_EDGE = 8  #触边障碍\n"
"uint8   TREELAWN     = 9  #绿植障碍\n"
"uint8   ULTRASONIC   = 10 #超声\n"
"\n"
"uint8 value\n"
;
  }

  static const char* value(const ::comm_msg::ultrasonicData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_msg::ultrasonicData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.usName);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultrasonicData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_msg::ultrasonicData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_msg::ultrasonicData_<ContainerAllocator>& v)
  {
    s << indent << "usName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.usName);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::comm_msg::coor2D_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_MSG_MESSAGE_ULTRASONICDATA_H
