# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from comm_srvs/visionLabelCfg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class visionLabelCfg(genpy.Message):
  _md5sum = "c57896cd544874b34ea95938d00716d9"
  _type = "comm_srvs/visionLabelCfg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint32[] vectDetLabel
uint32[] vectSegLabel

bool    isSupportThickPipe #是否支持粗水管类别
float32 thickPipeWidth     #粗水管宽度阈值"""
  __slots__ = ['vectDetLabel','vectSegLabel','isSupportThickPipe','thickPipeWidth']
  _slot_types = ['uint32[]','uint32[]','bool','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vectDetLabel,vectSegLabel,isSupportThickPipe,thickPipeWidth

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(visionLabelCfg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vectDetLabel is None:
        self.vectDetLabel = []
      if self.vectSegLabel is None:
        self.vectSegLabel = []
      if self.isSupportThickPipe is None:
        self.isSupportThickPipe = False
      if self.thickPipeWidth is None:
        self.thickPipeWidth = 0.
    else:
      self.vectDetLabel = []
      self.vectSegLabel = []
      self.isSupportThickPipe = False
      self.thickPipeWidth = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.vectDetLabel)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.vectDetLabel))
      length = len(self.vectSegLabel)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.vectSegLabel))
      _x = self
      buff.write(_get_struct_Bf().pack(_x.isSupportThickPipe, _x.thickPipeWidth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.vectDetLabel = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.vectSegLabel = s.unpack(str[start:end])
      _x = self
      start = end
      end += 5
      (_x.isSupportThickPipe, _x.thickPipeWidth,) = _get_struct_Bf().unpack(str[start:end])
      self.isSupportThickPipe = bool(self.isSupportThickPipe)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.vectDetLabel)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.vectDetLabel.tostring())
      length = len(self.vectSegLabel)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.vectSegLabel.tostring())
      _x = self
      buff.write(_get_struct_Bf().pack(_x.isSupportThickPipe, _x.thickPipeWidth))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.vectDetLabel = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.vectSegLabel = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      _x = self
      start = end
      end += 5
      (_x.isSupportThickPipe, _x.thickPipeWidth,) = _get_struct_Bf().unpack(str[start:end])
      self.isSupportThickPipe = bool(self.isSupportThickPipe)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bf = None
def _get_struct_Bf():
    global _struct_Bf
    if _struct_Bf is None:
        _struct_Bf = struct.Struct("<Bf")
    return _struct_Bf
